/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { joseObjectsVerify } from "../funcs/joseObjectsVerify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class JoseObjects extends ClientSDK {
  /**
   * Verify JOSE
   *
   * @remarks
   * This API verifies a JOSE object.
   */
  async verify(
    request: operations.JoseVerifyApiRequest,
    options?: RequestOptions,
  ): Promise<models.JoseVerifyResponse> {
    return unwrapAsync(joseObjectsVerify(
      this,
      request,
      options,
    ));
  }
}
