/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Authorization } from "./authorization.js";
import { AuthorizationEndpoint } from "./authorizationendpoint.js";
import { Ciba } from "./ciba.js";
import { ClientManagement } from "./clientmanagement.js";
import { Clients } from "./clients.js";
import { DeviceFlow } from "./deviceflow.js";
import { DynamicClientRegistration } from "./dynamicclientregistration.js";
import { DynamicClientRegistrations } from "./dynamicclientregistrations.js";
import { FederationEndpoint } from "./federationendpoint.js";
import { Federations } from "./federations.js";
import { GrantManagementEndpoint } from "./grantmanagementendpoint.js";
import { HardwareSecurityKey } from "./hardwaresecuritykey.js";
import { HardwareSecurityKeys } from "./hardwaresecuritykeys.js";
import { Introspection } from "./introspection.js";
import { IntrospectionEndpoint } from "./introspectionendpoint.js";
import { JoseObjects } from "./joseobjects.js";
import { JwkSets } from "./jwksets.js";
import { NativeSSO } from "./nativesso.js";
import { PushedAuthorization } from "./pushedauthorization.js";
import { Revocations } from "./revocations.js";
import { ServiceManagement } from "./servicemanagement.js";
import { Services } from "./services.js";
import { TokenEndpoint } from "./tokenendpoint.js";
import { TokenOperations } from "./tokenoperations.js";
import { Tokens } from "./tokens.js";
import { UserInfoEndpoint } from "./userinfoendpoint.js";
import { Utilities } from "./utilities.js";
import { UtilityEndpoints } from "./utilityendpoints.js";
import { VerifiableCredentialIssuer } from "./verifiablecredentialissuer.js";
import { VerifiableCredentialIssuers } from "./verifiablecredentialissuers.js";
import { VerifiableCredentials } from "./verifiablecredentials.js";

export class Authlete extends ClientSDK {
  private _serviceManagement?: ServiceManagement;
  get serviceManagement(): ServiceManagement {
    return (this._serviceManagement ??= new ServiceManagement(this._options));
  }

  private _services?: Services;
  get services(): Services {
    return (this._services ??= new Services(this._options));
  }

  private _clients?: Clients;
  get clients(): Clients {
    return (this._clients ??= new Clients(this._options));
  }

  private _clientManagement?: ClientManagement;
  get clientManagement(): ClientManagement {
    return (this._clientManagement ??= new ClientManagement(this._options));
  }

  private _authorization?: Authorization;
  get authorization(): Authorization {
    return (this._authorization ??= new Authorization(this._options));
  }

  private _authorizationEndpoint?: AuthorizationEndpoint;
  get authorizationEndpoint(): AuthorizationEndpoint {
    return (this._authorizationEndpoint ??= new AuthorizationEndpoint(
      this._options,
    ));
  }

  private _pushedAuthorization?: PushedAuthorization;
  get pushedAuthorization(): PushedAuthorization {
    return (this._pushedAuthorization ??= new PushedAuthorization(
      this._options,
    ));
  }

  private _tokens?: Tokens;
  get tokens(): Tokens {
    return (this._tokens ??= new Tokens(this._options));
  }

  private _introspection?: Introspection;
  get introspection(): Introspection {
    return (this._introspection ??= new Introspection(this._options));
  }

  private _introspectionEndpoint?: IntrospectionEndpoint;
  get introspectionEndpoint(): IntrospectionEndpoint {
    return (this._introspectionEndpoint ??= new IntrospectionEndpoint(
      this._options,
    ));
  }

  private _revocations?: Revocations;
  get revocations(): Revocations {
    return (this._revocations ??= new Revocations(this._options));
  }

  private _userInfoEndpoint?: UserInfoEndpoint;
  get userInfoEndpoint(): UserInfoEndpoint {
    return (this._userInfoEndpoint ??= new UserInfoEndpoint(this._options));
  }

  private _tokenEndpoint?: TokenEndpoint;
  get tokenEndpoint(): TokenEndpoint {
    return (this._tokenEndpoint ??= new TokenEndpoint(this._options));
  }

  private _grantManagementEndpoint?: GrantManagementEndpoint;
  get grantManagementEndpoint(): GrantManagementEndpoint {
    return (this._grantManagementEndpoint ??= new GrantManagementEndpoint(
      this._options,
    ));
  }

  private _jwkSets?: JwkSets;
  get jwkSets(): JwkSets {
    return (this._jwkSets ??= new JwkSets(this._options));
  }

  private _dynamicClientRegistrations?: DynamicClientRegistrations;
  get dynamicClientRegistrations(): DynamicClientRegistrations {
    return (this._dynamicClientRegistrations ??= new DynamicClientRegistrations(
      this._options,
    ));
  }

  private _dynamicClientRegistration?: DynamicClientRegistration;
  get dynamicClientRegistration(): DynamicClientRegistration {
    return (this._dynamicClientRegistration ??= new DynamicClientRegistration(
      this._options,
    ));
  }

  private _ciba?: Ciba;
  get ciba(): Ciba {
    return (this._ciba ??= new Ciba(this._options));
  }

  private _deviceFlow?: DeviceFlow;
  get deviceFlow(): DeviceFlow {
    return (this._deviceFlow ??= new DeviceFlow(this._options));
  }

  private _tokenOperations?: TokenOperations;
  get tokenOperations(): TokenOperations {
    return (this._tokenOperations ??= new TokenOperations(this._options));
  }

  private _joseObjects?: JoseObjects;
  get joseObjects(): JoseObjects {
    return (this._joseObjects ??= new JoseObjects(this._options));
  }

  private _federationEndpoint?: FederationEndpoint;
  get federationEndpoint(): FederationEndpoint {
    return (this._federationEndpoint ??= new FederationEndpoint(this._options));
  }

  private _federations?: Federations;
  get federations(): Federations {
    return (this._federations ??= new Federations(this._options));
  }

  private _utilityEndpoints?: UtilityEndpoints;
  get utilityEndpoints(): UtilityEndpoints {
    return (this._utilityEndpoints ??= new UtilityEndpoints(this._options));
  }

  private _hardwareSecurityKeys?: HardwareSecurityKeys;
  get hardwareSecurityKeys(): HardwareSecurityKeys {
    return (this._hardwareSecurityKeys ??= new HardwareSecurityKeys(
      this._options,
    ));
  }

  private _hardwareSecurityKey?: HardwareSecurityKey;
  get hardwareSecurityKey(): HardwareSecurityKey {
    return (this._hardwareSecurityKey ??= new HardwareSecurityKey(
      this._options,
    ));
  }

  private _utilities?: Utilities;
  get utilities(): Utilities {
    return (this._utilities ??= new Utilities(this._options));
  }

  private _verifiableCredentials?: VerifiableCredentials;
  get verifiableCredentials(): VerifiableCredentials {
    return (this._verifiableCredentials ??= new VerifiableCredentials(
      this._options,
    ));
  }

  private _verifiableCredentialIssuer?: VerifiableCredentialIssuer;
  get verifiableCredentialIssuer(): VerifiableCredentialIssuer {
    return (this._verifiableCredentialIssuer ??= new VerifiableCredentialIssuer(
      this._options,
    ));
  }

  private _verifiableCredentialIssuers?: VerifiableCredentialIssuers;
  get verifiableCredentialIssuers(): VerifiableCredentialIssuers {
    return (this._verifiableCredentialIssuers ??=
      new VerifiableCredentialIssuers(this._options));
  }

  private _nativeSSO?: NativeSSO;
  get nativeSSO(): NativeSSO {
    return (this._nativeSSO ??= new NativeSSO(this._options));
  }
}
