/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { servicesConfiguration } from "../funcs/servicesConfiguration.js";
import { servicesCreate } from "../funcs/servicesCreate.js";
import { servicesDelete } from "../funcs/servicesDelete.js";
import { servicesList } from "../funcs/servicesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Services extends ClientSDK {
  /**
   * List Services
   *
   * @remarks
   * Get a list of services.
   *
   * If the access token can only view or modify clients underneath a service, but does not
   * have access to view that service directly, a limited view of the service will be returned.
   * Otherwise, all properties of the service are returned.
   *
   * If the access token is an administrative token, this returns a list of all services on the Authlete instance.
   * Otherwise, all services that the access token can view, even in a limited fashion, are returned.
   */
  async list(
    request?: operations.ServiceGetListApiRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ServiceGetListResponse> {
    return unwrapAsync(servicesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Service
   *
   * @remarks
   * Create a new service.
   */
  async create(
    request?: models.ServiceInput | undefined,
    options?: RequestOptions,
  ): Promise<models.Service> {
    return unwrapAsync(servicesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Service ⚡
   *
   * @remarks
   * Delete a service.
   */
  async delete(
    request: operations.ServiceDeleteApiRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(servicesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Service Configuration
   *
   * @remarks
   * This API gathers configuration information about a service.
   * ### Description
   * This API is supposed to be called from within the implementation of the configuration endpoint of
   * the service where the service that supports OpenID Connect and [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1\_0.html)
   * must expose its configuration information in a JSON format. Details about the format are described
   * in "[3. OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1\_0.html#ProviderMetadata)"
   * in OpenID Connect Discovery 1.0.
   */
  async configuration(
    request: operations.ServiceConfigurationApiRequest,
    options?: RequestOptions,
  ): Promise<operations.ServiceConfigurationApiResponse> {
    return unwrapAsync(servicesConfiguration(
      this,
      request,
      options,
    ));
  }
}
