/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokenOperationsAuthTokenCreateBatchApi } from "../funcs/tokenOperationsAuthTokenCreateBatchApi.js";
import { tokenOperationsAuthTokenCreateBatchStatusApi } from "../funcs/tokenOperationsAuthTokenCreateBatchStatusApi.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TokenOperations extends ClientSDK {
  /**
   * Create Access Tokens in Batch
   *
   * @remarks
   * Create access tokens in batch.
   */
  async authTokenCreateBatchApi(
    request: operations.AuthTokenCreateBatchApiRequest,
    options?: RequestOptions,
  ): Promise<models.TokenCreateBatchResponse> {
    return unwrapAsync(tokenOperationsAuthTokenCreateBatchApi(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Batch Token Creation Status
   *
   * @remarks
   * Get the status of a batch token creation request.
   */
  async authTokenCreateBatchStatusApi(
    request: operations.AuthTokenCreateBatchStatusApiRequest,
    options?: RequestOptions,
  ): Promise<models.TokenCreateBatchStatusResponse> {
    return unwrapAsync(tokenOperationsAuthTokenCreateBatchStatusApi(
      this,
      request,
      options,
    ));
  }
}
