/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { utilityEndpointsInfoApi } from "../funcs/utilityEndpointsInfoApi.js";
import { utilityEndpointsMiscEchoApi } from "../funcs/utilityEndpointsMiscEchoApi.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UtilityEndpoints extends ClientSDK {
  /**
   * Get Server Metadata
   *
   * @remarks
   * get the server version and enabled features
   */
  async infoApi(
    options?: RequestOptions,
  ): Promise<models.InfoResponse> {
    return unwrapAsync(utilityEndpointsInfoApi(
      this,
      options,
    ));
  }

  /**
   * Echo
   *
   * @remarks
   * Echo test endpoint. Will return all path parameters in the request
   */
  async miscEchoApi(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(utilityEndpointsMiscEchoApi(
      this,
      options,
    ));
  }
}
