/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { utilityEcho } from "../funcs/utilityEcho.js";
import { utilityInfo } from "../funcs/utilityInfo.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Utility extends ClientSDK {
  /**
   * Get Server Metadata
   *
   * @remarks
   * get the server version and enabled features
   */
  async info(
    options?: RequestOptions,
  ): Promise<models.InfoResponse> {
    return unwrapAsync(utilityInfo(
      this,
      options,
    ));
  }

  /**
   * Echo
   *
   * @remarks
   * Echo test endpoint. Will return all path parameters in the request
   */
  async echo(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(utilityEcho(
      this,
      options,
    ));
  }
}
