/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the authlete SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx serviceManagementServiceGetApi.example.ts
 */

import { Authlete } from "authlete";

const authlete = new Authlete({
  security: {
    authlete: process.env["AUTHLETE_AUTHLETE"] ?? "",
  },
});

async function main() {
  const result = await authlete.serviceGetApi({
    serviceId: "<id>",
  });

  console.log(result);
}

main().catch(console.error);
