workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Authlete API Explorer:
        inputs:
            - location: ../../../../../../../../Documents/new-api-doc2/app/specs/shared/3.0.15/en3-referenced.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/authlete/sdk-workspace/authlete-api-explorer
targets:
    authlete-test:
        target: typescript
        source: Authlete API Explorer
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/authlete/sdk-workspace/authlete-api-explorer-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
