/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AuthIntrospectionStandardApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  standardIntrospectionRequest: models.StandardIntrospectionRequest;
};

/** @internal */
export type AuthIntrospectionStandardApiRequest$Outbound = {
  serviceId: string;
  standard_introspection_request: models.StandardIntrospectionRequest$Outbound;
};

/** @internal */
export const AuthIntrospectionStandardApiRequest$outboundSchema: z.ZodType<
  AuthIntrospectionStandardApiRequest$Outbound,
  z.ZodTypeDef,
  AuthIntrospectionStandardApiRequest
> = z.object({
  serviceId: z.string(),
  standardIntrospectionRequest:
    models.StandardIntrospectionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    standardIntrospectionRequest: "standard_introspection_request",
  });
});

export function authIntrospectionStandardApiRequestToJSON(
  authIntrospectionStandardApiRequest: AuthIntrospectionStandardApiRequest,
): string {
  return JSON.stringify(
    AuthIntrospectionStandardApiRequest$outboundSchema.parse(
      authIntrospectionStandardApiRequest,
    ),
  );
}
