/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AuthAuthorizationFailApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationFailRequest: models.AuthorizationFailRequest;
};

/** @internal */
export type AuthAuthorizationFailApiRequest$Outbound = {
  serviceId: string;
  authorization_fail_request: models.AuthorizationFailRequest$Outbound;
};

/** @internal */
export const AuthAuthorizationFailApiRequest$outboundSchema: z.ZodType<
  AuthAuthorizationFailApiRequest$Outbound,
  z.ZodTypeDef,
  AuthAuthorizationFailApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationFailRequest: models.AuthorizationFailRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationFailRequest: "authorization_fail_request",
  });
});

export function authAuthorizationFailApiRequestToJSON(
  authAuthorizationFailApiRequest: AuthAuthorizationFailApiRequest,
): string {
  return JSON.stringify(
    AuthAuthorizationFailApiRequest$outboundSchema.parse(
      authAuthorizationFailApiRequest,
    ),
  );
}
