/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AuthAuthorizationIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationIssueRequest: models.AuthorizationIssueRequest;
};

/** @internal */
export const AuthAuthorizationIssueApiRequest$inboundSchema: z.ZodType<
  AuthAuthorizationIssueApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  authorization_issue_request: models.AuthorizationIssueRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "authorization_issue_request": "authorizationIssueRequest",
  });
});

/** @internal */
export type AuthAuthorizationIssueApiRequest$Outbound = {
  serviceId: string;
  authorization_issue_request: models.AuthorizationIssueRequest$Outbound;
};

/** @internal */
export const AuthAuthorizationIssueApiRequest$outboundSchema: z.ZodType<
  AuthAuthorizationIssueApiRequest$Outbound,
  z.ZodTypeDef,
  AuthAuthorizationIssueApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationIssueRequest: models.AuthorizationIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationIssueRequest: "authorization_issue_request",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthAuthorizationIssueApiRequest$ {
  /** @deprecated use `AuthAuthorizationIssueApiRequest$inboundSchema` instead. */
  export const inboundSchema = AuthAuthorizationIssueApiRequest$inboundSchema;
  /** @deprecated use `AuthAuthorizationIssueApiRequest$outboundSchema` instead. */
  export const outboundSchema = AuthAuthorizationIssueApiRequest$outboundSchema;
  /** @deprecated use `AuthAuthorizationIssueApiRequest$Outbound` instead. */
  export type Outbound = AuthAuthorizationIssueApiRequest$Outbound;
}

export function authAuthorizationIssueApiRequestToJSON(
  authAuthorizationIssueApiRequest: AuthAuthorizationIssueApiRequest,
): string {
  return JSON.stringify(
    AuthAuthorizationIssueApiRequest$outboundSchema.parse(
      authAuthorizationIssueApiRequest,
    ),
  );
}

export function authAuthorizationIssueApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<AuthAuthorizationIssueApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthAuthorizationIssueApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthAuthorizationIssueApiRequest' from JSON`,
  );
}
