/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AuthorizationTicketInfoPostApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationTicketInfoRequest: models.AuthorizationTicketInfoRequest;
};

/** @internal */
export type AuthorizationTicketInfoPostApiRequest$Outbound = {
  serviceId: string;
  authorization_ticket_info_request:
    models.AuthorizationTicketInfoRequest$Outbound;
};

/** @internal */
export const AuthorizationTicketInfoPostApiRequest$outboundSchema: z.ZodType<
  AuthorizationTicketInfoPostApiRequest$Outbound,
  z.ZodTypeDef,
  AuthorizationTicketInfoPostApiRequest
> = z.object({
  serviceId: z.string(),
  authorizationTicketInfoRequest:
    models.AuthorizationTicketInfoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationTicketInfoRequest: "authorization_ticket_info_request",
  });
});

export function authorizationTicketInfoPostApiRequestToJSON(
  authorizationTicketInfoPostApiRequest: AuthorizationTicketInfoPostApiRequest,
): string {
  return JSON.stringify(
    AuthorizationTicketInfoPostApiRequest$outboundSchema.parse(
      authorizationTicketInfoPostApiRequest,
    ),
  );
}
