/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AuthTokenIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenIssueRequest: models.TokenIssueRequest;
};

/** @internal */
export type AuthTokenIssueApiRequest$Outbound = {
  serviceId: string;
  token_issue_request: models.TokenIssueRequest$Outbound;
};

/** @internal */
export const AuthTokenIssueApiRequest$outboundSchema: z.ZodType<
  AuthTokenIssueApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenIssueApiRequest
> = z.object({
  serviceId: z.string(),
  tokenIssueRequest: models.TokenIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenIssueRequest: "token_issue_request",
  });
});

export function authTokenIssueApiRequestToJSON(
  authTokenIssueApiRequest: AuthTokenIssueApiRequest,
): string {
  return JSON.stringify(
    AuthTokenIssueApiRequest$outboundSchema.parse(authTokenIssueApiRequest),
  );
}
