/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AuthTokenCreateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenCreateRequest: models.TokenCreateRequest;
};

/** @internal */
export type AuthTokenCreateApiRequest$Outbound = {
  serviceId: string;
  token_create_request: models.TokenCreateRequest$Outbound;
};

/** @internal */
export const AuthTokenCreateApiRequest$outboundSchema: z.ZodType<
  AuthTokenCreateApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenCreateApiRequest
> = z.object({
  serviceId: z.string(),
  tokenCreateRequest: models.TokenCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenCreateRequest: "token_create_request",
  });
});

export function authTokenCreateApiRequestToJSON(
  authTokenCreateApiRequest: AuthTokenCreateApiRequest,
): string {
  return JSON.stringify(
    AuthTokenCreateApiRequest$outboundSchema.parse(authTokenCreateApiRequest),
  );
}
