/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type AuthTokenUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  tokenUpdateRequest: models.TokenUpdateRequest;
};

/** @internal */
export type AuthTokenUpdateApiRequest$Outbound = {
  serviceId: string;
  token_update_request: models.TokenUpdateRequest$Outbound;
};

/** @internal */
export const AuthTokenUpdateApiRequest$outboundSchema: z.ZodType<
  AuthTokenUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  AuthTokenUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  tokenUpdateRequest: models.TokenUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    tokenUpdateRequest: "token_update_request",
  });
});

export function authTokenUpdateApiRequestToJSON(
  authTokenUpdateApiRequest: AuthTokenUpdateApiRequest,
): string {
  return JSON.stringify(
    AuthTokenUpdateApiRequest$outboundSchema.parse(authTokenUpdateApiRequest),
  );
}
