/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type BackchannelAuthenticationCompleteApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  backchannelAuthenticationCompleteRequest:
    models.BackchannelAuthenticationCompleteRequest;
};

/** @internal */
export type BackchannelAuthenticationCompleteApiRequest$Outbound = {
  serviceId: string;
  backchannel_authentication_complete_request:
    models.BackchannelAuthenticationCompleteRequest$Outbound;
};

/** @internal */
export const BackchannelAuthenticationCompleteApiRequest$outboundSchema:
  z.ZodType<
    BackchannelAuthenticationCompleteApiRequest$Outbound,
    z.ZodTypeDef,
    BackchannelAuthenticationCompleteApiRequest
  > = z.object({
    serviceId: z.string(),
    backchannelAuthenticationCompleteRequest:
      models.BackchannelAuthenticationCompleteRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      backchannelAuthenticationCompleteRequest:
        "backchannel_authentication_complete_request",
    });
  });

export function backchannelAuthenticationCompleteApiRequestToJSON(
  backchannelAuthenticationCompleteApiRequest:
    BackchannelAuthenticationCompleteApiRequest,
): string {
  return JSON.stringify(
    BackchannelAuthenticationCompleteApiRequest$outboundSchema.parse(
      backchannelAuthenticationCompleteApiRequest,
    ),
  );
}
