/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ClientUpdateApiFormRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   */
  clientId: string;
  requestBody?: { [k: string]: any } | undefined;
};

/** @internal */
export type ClientUpdateApiFormRequest$Outbound = {
  serviceId: string;
  clientId: string;
  RequestBody?: { [k: string]: any } | undefined;
};

/** @internal */
export const ClientUpdateApiFormRequest$outboundSchema: z.ZodType<
  ClientUpdateApiFormRequest$Outbound,
  z.ZodTypeDef,
  ClientUpdateApiFormRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  requestBody: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientUpdateApiFormRequestToJSON(
  clientUpdateApiFormRequest: ClientUpdateApiFormRequest,
): string {
  return JSON.stringify(
    ClientUpdateApiFormRequest$outboundSchema.parse(clientUpdateApiFormRequest),
  );
}
