/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ClientAuthorizationGetListBySubjectApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
  /**
   * Unique ID of a client developer.
   *
   * @remarks
   */
  developer?: string | undefined;
  /**
   * Start index of search results (inclusive). The default value is 0.
   */
  start?: number | undefined;
  /**
   * End index of search results (exclusive). The default value is 5.
   *
   * @remarks
   */
  end?: number | undefined;
};

/** @internal */
export type ClientAuthorizationGetListBySubjectApiRequest$Outbound = {
  serviceId: string;
  subject: string;
  developer?: string | undefined;
  start?: number | undefined;
  end?: number | undefined;
};

/** @internal */
export const ClientAuthorizationGetListBySubjectApiRequest$outboundSchema:
  z.ZodType<
    ClientAuthorizationGetListBySubjectApiRequest$Outbound,
    z.ZodTypeDef,
    ClientAuthorizationGetListBySubjectApiRequest
  > = z.object({
    serviceId: z.string(),
    subject: z.string(),
    developer: z.string().optional(),
    start: z.number().int().optional(),
    end: z.number().int().optional(),
  });

export function clientAuthorizationGetListBySubjectApiRequestToJSON(
  clientAuthorizationGetListBySubjectApiRequest:
    ClientAuthorizationGetListBySubjectApiRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationGetListBySubjectApiRequest$outboundSchema.parse(
      clientAuthorizationGetListBySubjectApiRequest,
    ),
  );
}
