/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type ClientCreateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  client?: models.ClientInput | undefined;
};

/** @internal */
export type ClientCreateApiRequest$Outbound = {
  serviceId: string;
  client?: models.ClientInput$Outbound | undefined;
};

/** @internal */
export const ClientCreateApiRequest$outboundSchema: z.ZodType<
  ClientCreateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientCreateApiRequest
> = z.object({
  serviceId: z.string(),
  client: models.ClientInput$outboundSchema.optional(),
});

export function clientCreateApiRequestToJSON(
  clientCreateApiRequest: ClientCreateApiRequest,
): string {
  return JSON.stringify(
    ClientCreateApiRequest$outboundSchema.parse(clientCreateApiRequest),
  );
}
