/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ClientExtensionRequestablesScopesUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  clientExtensionRequestableScopesUpdateRequest:
    models.ClientExtensionRequestableScopesUpdateRequest;
};

/** @internal */
export type ClientExtensionRequestablesScopesUpdateApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  client_extension_requestable_scopes_update_request:
    models.ClientExtensionRequestableScopesUpdateRequest$Outbound;
};

/** @internal */
export const ClientExtensionRequestablesScopesUpdateApiRequest$outboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesUpdateApiRequest$Outbound,
    z.ZodTypeDef,
    ClientExtensionRequestablesScopesUpdateApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    clientExtensionRequestableScopesUpdateRequest:
      models.ClientExtensionRequestableScopesUpdateRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      clientExtensionRequestableScopesUpdateRequest:
        "client_extension_requestable_scopes_update_request",
    });
  });

export function clientExtensionRequestablesScopesUpdateApiRequestToJSON(
  clientExtensionRequestablesScopesUpdateApiRequest:
    ClientExtensionRequestablesScopesUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientExtensionRequestablesScopesUpdateApiRequest$outboundSchema.parse(
      clientExtensionRequestablesScopesUpdateApiRequest,
    ),
  );
}
