/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ClientGrantedScopesGetBySubjectApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject: string;
};

/** @internal */
export type ClientGrantedScopesGetBySubjectApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
  subject: string;
};

/** @internal */
export const ClientGrantedScopesGetBySubjectApiRequest$outboundSchema:
  z.ZodType<
    ClientGrantedScopesGetBySubjectApiRequest$Outbound,
    z.ZodTypeDef,
    ClientGrantedScopesGetBySubjectApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    subject: z.string(),
  });

export function clientGrantedScopesGetBySubjectApiRequestToJSON(
  clientGrantedScopesGetBySubjectApiRequest:
    ClientGrantedScopesGetBySubjectApiRequest,
): string {
  return JSON.stringify(
    ClientGrantedScopesGetBySubjectApiRequest$outboundSchema.parse(
      clientGrantedScopesGetBySubjectApiRequest,
    ),
  );
}
