/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ClientAuthorizationDeleteApiPostRequestBody = {
  /**
   * Unique user ID of an end-user.
   */
  subject: string;
};

export type ClientAuthorizationDeleteApiPostRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  requestBody: ClientAuthorizationDeleteApiPostRequestBody;
};

/** @internal */
export type ClientAuthorizationDeleteApiPostRequestBody$Outbound = {
  subject: string;
};

/** @internal */
export const ClientAuthorizationDeleteApiPostRequestBody$outboundSchema:
  z.ZodType<
    ClientAuthorizationDeleteApiPostRequestBody$Outbound,
    z.ZodTypeDef,
    ClientAuthorizationDeleteApiPostRequestBody
  > = z.object({
    subject: z.string(),
  });

export function clientAuthorizationDeleteApiPostRequestBodyToJSON(
  clientAuthorizationDeleteApiPostRequestBody:
    ClientAuthorizationDeleteApiPostRequestBody,
): string {
  return JSON.stringify(
    ClientAuthorizationDeleteApiPostRequestBody$outboundSchema.parse(
      clientAuthorizationDeleteApiPostRequestBody,
    ),
  );
}

/** @internal */
export type ClientAuthorizationDeleteApiPostRequest$Outbound = {
  serviceId: string;
  clientId: string;
  RequestBody: ClientAuthorizationDeleteApiPostRequestBody$Outbound;
};

/** @internal */
export const ClientAuthorizationDeleteApiPostRequest$outboundSchema: z.ZodType<
  ClientAuthorizationDeleteApiPostRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationDeleteApiPostRequest
> = z.object({
  serviceId: z.string(),
  clientId: z.string(),
  requestBody: z.lazy(() =>
    ClientAuthorizationDeleteApiPostRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientAuthorizationDeleteApiPostRequestToJSON(
  clientAuthorizationDeleteApiPostRequest:
    ClientAuthorizationDeleteApiPostRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationDeleteApiPostRequest$outboundSchema.parse(
      clientAuthorizationDeleteApiPostRequest,
    ),
  );
}
