/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ClientExtensionRequestablesScopesGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
};

/** @internal */
export type ClientExtensionRequestablesScopesGetApiRequest$Outbound = {
  serviceId: string;
  clientId: string;
};

/** @internal */
export const ClientExtensionRequestablesScopesGetApiRequest$outboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesGetApiRequest$Outbound,
    z.ZodTypeDef,
    ClientExtensionRequestablesScopesGetApiRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
  });

export function clientExtensionRequestablesScopesGetApiRequestToJSON(
  clientExtensionRequestablesScopesGetApiRequest:
    ClientExtensionRequestablesScopesGetApiRequest,
): string {
  return JSON.stringify(
    ClientExtensionRequestablesScopesGetApiRequest$outboundSchema.parse(
      clientExtensionRequestablesScopesGetApiRequest,
    ),
  );
}
