/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ClientGetListApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * The developer of client applications. The default value is null. If this parameter is not set
   *
   * @remarks
   * to `null`, client application of the specified developer are returned. Otherwise, all client
   * applications that belong to the service are returned.
   */
  developer?: string | undefined;
  /**
   * Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
   */
  start?: number | undefined;
  /**
   * End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
   */
  end?: number | undefined;
};

/** @internal */
export type ClientGetListApiRequest$Outbound = {
  serviceId: string;
  developer?: string | undefined;
  start?: number | undefined;
  end?: number | undefined;
};

/** @internal */
export const ClientGetListApiRequest$outboundSchema: z.ZodType<
  ClientGetListApiRequest$Outbound,
  z.ZodTypeDef,
  ClientGetListApiRequest
> = z.object({
  serviceId: z.string(),
  developer: z.string().optional(),
  start: z.number().int().optional(),
  end: z.number().int().optional(),
});

export function clientGetListApiRequestToJSON(
  clientGetListApiRequest: ClientGetListApiRequest,
): string {
  return JSON.stringify(
    ClientGetListApiRequest$outboundSchema.parse(clientGetListApiRequest),
  );
}
