/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ClientAuthorizationGetListApiPostRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  clientAuthorizationGetListRequest: models.ClientAuthorizationGetListRequest;
};

/** @internal */
export type ClientAuthorizationGetListApiPostRequest$Outbound = {
  serviceId: string;
  client_authorization_get_list_request:
    models.ClientAuthorizationGetListRequest$Outbound;
};

/** @internal */
export const ClientAuthorizationGetListApiPostRequest$outboundSchema: z.ZodType<
  ClientAuthorizationGetListApiPostRequest$Outbound,
  z.ZodTypeDef,
  ClientAuthorizationGetListApiPostRequest
> = z.object({
  serviceId: z.string(),
  clientAuthorizationGetListRequest:
    models.ClientAuthorizationGetListRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    clientAuthorizationGetListRequest: "client_authorization_get_list_request",
  });
});

export function clientAuthorizationGetListApiPostRequestToJSON(
  clientAuthorizationGetListApiPostRequest:
    ClientAuthorizationGetListApiPostRequest,
): string {
  return JSON.stringify(
    ClientAuthorizationGetListApiPostRequest$outboundSchema.parse(
      clientAuthorizationGetListApiPostRequest,
    ),
  );
}
