/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ClientRegistrationGetApiRequestBody = {
  /**
   * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
   *
   * @remarks
   * (OAuth 2.0 Dynamic Client Registration Protocol).
   */
  json?: string | undefined;
  /**
   * The client registration access token. Used only for GET, UPDATE, and DELETE requests.
   *
   * @remarks
   */
  token: string;
  /**
   * The client's identifier. Used for GET, UPDATE, and DELETE requests
   *
   * @remarks
   */
  clientId: string;
};

export type ClientRegistrationGetApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  requestBody: ClientRegistrationGetApiRequestBody;
};

/** @internal */
export const ClientRegistrationGetApiRequestBody$inboundSchema: z.ZodType<
  ClientRegistrationGetApiRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  json: z.string().optional(),
  token: z.string(),
  clientId: z.string(),
});

/** @internal */
export type ClientRegistrationGetApiRequestBody$Outbound = {
  json?: string | undefined;
  token: string;
  clientId: string;
};

/** @internal */
export const ClientRegistrationGetApiRequestBody$outboundSchema: z.ZodType<
  ClientRegistrationGetApiRequestBody$Outbound,
  z.ZodTypeDef,
  ClientRegistrationGetApiRequestBody
> = z.object({
  json: z.string().optional(),
  token: z.string(),
  clientId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClientRegistrationGetApiRequestBody$ {
  /** @deprecated use `ClientRegistrationGetApiRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    ClientRegistrationGetApiRequestBody$inboundSchema;
  /** @deprecated use `ClientRegistrationGetApiRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    ClientRegistrationGetApiRequestBody$outboundSchema;
  /** @deprecated use `ClientRegistrationGetApiRequestBody$Outbound` instead. */
  export type Outbound = ClientRegistrationGetApiRequestBody$Outbound;
}

export function clientRegistrationGetApiRequestBodyToJSON(
  clientRegistrationGetApiRequestBody: ClientRegistrationGetApiRequestBody,
): string {
  return JSON.stringify(
    ClientRegistrationGetApiRequestBody$outboundSchema.parse(
      clientRegistrationGetApiRequestBody,
    ),
  );
}

export function clientRegistrationGetApiRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<ClientRegistrationGetApiRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientRegistrationGetApiRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientRegistrationGetApiRequestBody' from JSON`,
  );
}

/** @internal */
export const ClientRegistrationGetApiRequest$inboundSchema: z.ZodType<
  ClientRegistrationGetApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  RequestBody: z.lazy(() => ClientRegistrationGetApiRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type ClientRegistrationGetApiRequest$Outbound = {
  serviceId: string;
  RequestBody: ClientRegistrationGetApiRequestBody$Outbound;
};

/** @internal */
export const ClientRegistrationGetApiRequest$outboundSchema: z.ZodType<
  ClientRegistrationGetApiRequest$Outbound,
  z.ZodTypeDef,
  ClientRegistrationGetApiRequest
> = z.object({
  serviceId: z.string(),
  requestBody: z.lazy(() => ClientRegistrationGetApiRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClientRegistrationGetApiRequest$ {
  /** @deprecated use `ClientRegistrationGetApiRequest$inboundSchema` instead. */
  export const inboundSchema = ClientRegistrationGetApiRequest$inboundSchema;
  /** @deprecated use `ClientRegistrationGetApiRequest$outboundSchema` instead. */
  export const outboundSchema = ClientRegistrationGetApiRequest$outboundSchema;
  /** @deprecated use `ClientRegistrationGetApiRequest$Outbound` instead. */
  export type Outbound = ClientRegistrationGetApiRequest$Outbound;
}

export function clientRegistrationGetApiRequestToJSON(
  clientRegistrationGetApiRequest: ClientRegistrationGetApiRequest,
): string {
  return JSON.stringify(
    ClientRegistrationGetApiRequest$outboundSchema.parse(
      clientRegistrationGetApiRequest,
    ),
  );
}

export function clientRegistrationGetApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<ClientRegistrationGetApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientRegistrationGetApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientRegistrationGetApiRequest' from JSON`,
  );
}
