/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ClientRegistrationUpdateApiRequestBody = {
  /**
   * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
   *
   * @remarks
   * (OAuth 2.0 Dynamic Client Registration Protocol).
   */
  json: string;
  /**
   * The client registration access token. Used only for GET, UPDATE, and DELETE requests.
   *
   * @remarks
   */
  token: string;
  /**
   * The client's identifier. Used for GET, UPDATE, and DELETE requests
   *
   * @remarks
   */
  clientId: string;
};

export type ClientRegistrationUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  requestBody: ClientRegistrationUpdateApiRequestBody;
};

/** @internal */
export type ClientRegistrationUpdateApiRequestBody$Outbound = {
  json: string;
  token: string;
  clientId: string;
};

/** @internal */
export const ClientRegistrationUpdateApiRequestBody$outboundSchema: z.ZodType<
  ClientRegistrationUpdateApiRequestBody$Outbound,
  z.ZodTypeDef,
  ClientRegistrationUpdateApiRequestBody
> = z.object({
  json: z.string(),
  token: z.string(),
  clientId: z.string(),
});

export function clientRegistrationUpdateApiRequestBodyToJSON(
  clientRegistrationUpdateApiRequestBody:
    ClientRegistrationUpdateApiRequestBody,
): string {
  return JSON.stringify(
    ClientRegistrationUpdateApiRequestBody$outboundSchema.parse(
      clientRegistrationUpdateApiRequestBody,
    ),
  );
}

/** @internal */
export type ClientRegistrationUpdateApiRequest$Outbound = {
  serviceId: string;
  RequestBody: ClientRegistrationUpdateApiRequestBody$Outbound;
};

/** @internal */
export const ClientRegistrationUpdateApiRequest$outboundSchema: z.ZodType<
  ClientRegistrationUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ClientRegistrationUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  requestBody: z.lazy(() =>
    ClientRegistrationUpdateApiRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function clientRegistrationUpdateApiRequestToJSON(
  clientRegistrationUpdateApiRequest: ClientRegistrationUpdateApiRequest,
): string {
  return JSON.stringify(
    ClientRegistrationUpdateApiRequest$outboundSchema.parse(
      clientRegistrationUpdateApiRequest,
    ),
  );
}
