/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type ClientExtensionRequestablesScopesUpdateApiPostRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  /**
   * A client ID.
   *
   * @remarks
   */
  clientId: string;
  clientExtensionRequestableScopesUpdateRequest:
    models.ClientExtensionRequestableScopesUpdateRequest;
};

/** @internal */
export type ClientExtensionRequestablesScopesUpdateApiPostRequest$Outbound = {
  serviceId: string;
  clientId: string;
  client_extension_requestable_scopes_update_request:
    models.ClientExtensionRequestableScopesUpdateRequest$Outbound;
};

/** @internal */
export const ClientExtensionRequestablesScopesUpdateApiPostRequest$outboundSchema:
  z.ZodType<
    ClientExtensionRequestablesScopesUpdateApiPostRequest$Outbound,
    z.ZodTypeDef,
    ClientExtensionRequestablesScopesUpdateApiPostRequest
  > = z.object({
    serviceId: z.string(),
    clientId: z.string(),
    clientExtensionRequestableScopesUpdateRequest:
      models.ClientExtensionRequestableScopesUpdateRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      clientExtensionRequestableScopesUpdateRequest:
        "client_extension_requestable_scopes_update_request",
    });
  });

export function clientExtensionRequestablesScopesUpdateApiPostRequestToJSON(
  clientExtensionRequestablesScopesUpdateApiPostRequest:
    ClientExtensionRequestablesScopesUpdateApiPostRequest,
): string {
  return JSON.stringify(
    ClientExtensionRequestablesScopesUpdateApiPostRequest$outboundSchema.parse(
      clientExtensionRequestablesScopesUpdateApiPostRequest,
    ),
  );
}
