/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeviceAuthorizationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  deviceAuthorizationRequest: models.DeviceAuthorizationRequest;
};

/** @internal */
export const DeviceAuthorizationApiRequest$inboundSchema: z.ZodType<
  DeviceAuthorizationApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  device_authorization_request: models.DeviceAuthorizationRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "device_authorization_request": "deviceAuthorizationRequest",
  });
});

/** @internal */
export type DeviceAuthorizationApiRequest$Outbound = {
  serviceId: string;
  device_authorization_request: models.DeviceAuthorizationRequest$Outbound;
};

/** @internal */
export const DeviceAuthorizationApiRequest$outboundSchema: z.ZodType<
  DeviceAuthorizationApiRequest$Outbound,
  z.ZodTypeDef,
  DeviceAuthorizationApiRequest
> = z.object({
  serviceId: z.string(),
  deviceAuthorizationRequest: models.DeviceAuthorizationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deviceAuthorizationRequest: "device_authorization_request",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeviceAuthorizationApiRequest$ {
  /** @deprecated use `DeviceAuthorizationApiRequest$inboundSchema` instead. */
  export const inboundSchema = DeviceAuthorizationApiRequest$inboundSchema;
  /** @deprecated use `DeviceAuthorizationApiRequest$outboundSchema` instead. */
  export const outboundSchema = DeviceAuthorizationApiRequest$outboundSchema;
  /** @deprecated use `DeviceAuthorizationApiRequest$Outbound` instead. */
  export type Outbound = DeviceAuthorizationApiRequest$Outbound;
}

export function deviceAuthorizationApiRequestToJSON(
  deviceAuthorizationApiRequest: DeviceAuthorizationApiRequest,
): string {
  return JSON.stringify(
    DeviceAuthorizationApiRequest$outboundSchema.parse(
      deviceAuthorizationApiRequest,
    ),
  );
}

export function deviceAuthorizationApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeviceAuthorizationApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceAuthorizationApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceAuthorizationApiRequest' from JSON`,
  );
}
