/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type FederationRegistrationApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  federationRegistrationRequest: models.FederationRegistrationRequest;
};

/** @internal */
export type FederationRegistrationApiRequest$Outbound = {
  serviceId: string;
  federation_registration_request:
    models.FederationRegistrationRequest$Outbound;
};

/** @internal */
export const FederationRegistrationApiRequest$outboundSchema: z.ZodType<
  FederationRegistrationApiRequest$Outbound,
  z.ZodTypeDef,
  FederationRegistrationApiRequest
> = z.object({
  serviceId: z.string(),
  federationRegistrationRequest:
    models.FederationRegistrationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    federationRegistrationRequest: "federation_registration_request",
  });
});

export function federationRegistrationApiRequestToJSON(
  federationRegistrationApiRequest: FederationRegistrationApiRequest,
): string {
  return JSON.stringify(
    FederationRegistrationApiRequest$outboundSchema.parse(
      federationRegistrationApiRequest,
    ),
  );
}
