/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type GetAuthorizationTicketInfoRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationTicketInfoRequest: models.AuthorizationTicketInfoRequest;
};

/** @internal */
export type GetAuthorizationTicketInfoRequest$Outbound = {
  serviceId: string;
  authorization_ticket_info_request:
    models.AuthorizationTicketInfoRequest$Outbound;
};

/** @internal */
export const GetAuthorizationTicketInfoRequest$outboundSchema: z.ZodType<
  GetAuthorizationTicketInfoRequest$Outbound,
  z.ZodTypeDef,
  GetAuthorizationTicketInfoRequest
> = z.object({
  serviceId: z.string(),
  authorizationTicketInfoRequest:
    models.AuthorizationTicketInfoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationTicketInfoRequest: "authorization_ticket_info_request",
  });
});

export function getAuthorizationTicketInfoRequestToJSON(
  getAuthorizationTicketInfoRequest: GetAuthorizationTicketInfoRequest,
): string {
  return JSON.stringify(
    GetAuthorizationTicketInfoRequest$outboundSchema.parse(
      getAuthorizationTicketInfoRequest,
    ),
  );
}
