/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetApiLifecycleHealthcheckRequest = {
  /**
   * If `true`, perform extended health checks (e.g. database connectivity).
   *
   * @remarks
   */
  extended?: boolean | undefined;
};

/** @internal */
export type GetApiLifecycleHealthcheckRequest$Outbound = {
  extended?: boolean | undefined;
};

/** @internal */
export const GetApiLifecycleHealthcheckRequest$outboundSchema: z.ZodType<
  GetApiLifecycleHealthcheckRequest$Outbound,
  z.ZodTypeDef,
  GetApiLifecycleHealthcheckRequest
> = z.object({
  extended: z.boolean().optional(),
});

export function getApiLifecycleHealthcheckRequestToJSON(
  getApiLifecycleHealthcheckRequest: GetApiLifecycleHealthcheckRequest,
): string {
  return JSON.stringify(
    GetApiLifecycleHealthcheckRequest$outboundSchema.parse(
      getApiLifecycleHealthcheckRequest,
    ),
  );
}
