/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAuthorizationTicketInfoRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  authorizationTicketInfoRequest: models.AuthorizationTicketInfoRequest;
};

/** @internal */
export const GetAuthorizationTicketInfoRequest$inboundSchema: z.ZodType<
  GetAuthorizationTicketInfoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  authorization_ticket_info_request:
    models.AuthorizationTicketInfoRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "authorization_ticket_info_request": "authorizationTicketInfoRequest",
  });
});

/** @internal */
export type GetAuthorizationTicketInfoRequest$Outbound = {
  serviceId: string;
  authorization_ticket_info_request:
    models.AuthorizationTicketInfoRequest$Outbound;
};

/** @internal */
export const GetAuthorizationTicketInfoRequest$outboundSchema: z.ZodType<
  GetAuthorizationTicketInfoRequest$Outbound,
  z.ZodTypeDef,
  GetAuthorizationTicketInfoRequest
> = z.object({
  serviceId: z.string(),
  authorizationTicketInfoRequest:
    models.AuthorizationTicketInfoRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authorizationTicketInfoRequest: "authorization_ticket_info_request",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAuthorizationTicketInfoRequest$ {
  /** @deprecated use `GetAuthorizationTicketInfoRequest$inboundSchema` instead. */
  export const inboundSchema = GetAuthorizationTicketInfoRequest$inboundSchema;
  /** @deprecated use `GetAuthorizationTicketInfoRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetAuthorizationTicketInfoRequest$outboundSchema;
  /** @deprecated use `GetAuthorizationTicketInfoRequest$Outbound` instead. */
  export type Outbound = GetAuthorizationTicketInfoRequest$Outbound;
}

export function getAuthorizationTicketInfoRequestToJSON(
  getAuthorizationTicketInfoRequest: GetAuthorizationTicketInfoRequest,
): string {
  return JSON.stringify(
    GetAuthorizationTicketInfoRequest$outboundSchema.parse(
      getAuthorizationTicketInfoRequest,
    ),
  );
}

export function getAuthorizationTicketInfoRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAuthorizationTicketInfoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAuthorizationTicketInfoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAuthorizationTicketInfoRequest' from JSON`,
  );
}
