/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type HskGetListApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
};

/** @internal */
export type HskGetListApiRequest$Outbound = {
  serviceId: string;
};

/** @internal */
export const HskGetListApiRequest$outboundSchema: z.ZodType<
  HskGetListApiRequest$Outbound,
  z.ZodTypeDef,
  HskGetListApiRequest
> = z.object({
  serviceId: z.string(),
});

export function hskGetListApiRequestToJSON(
  hskGetListApiRequest: HskGetListApiRequest,
): string {
  return JSON.stringify(
    HskGetListApiRequest$outboundSchema.parse(hskGetListApiRequest),
  );
}
