/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type JoseVerifyApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  joseVerifyRequest?: models.JoseVerifyRequest | undefined;
};

/** @internal */
export type JoseVerifyApiRequest$Outbound = {
  serviceId: string;
  jose_verify_request?: models.JoseVerifyRequest$Outbound | undefined;
};

/** @internal */
export const JoseVerifyApiRequest$outboundSchema: z.ZodType<
  JoseVerifyApiRequest$Outbound,
  z.ZodTypeDef,
  JoseVerifyApiRequest
> = z.object({
  serviceId: z.string(),
  joseVerifyRequest: models.JoseVerifyRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    joseVerifyRequest: "jose_verify_request",
  });
});

export function joseVerifyApiRequestToJSON(
  joseVerifyApiRequest: JoseVerifyApiRequest,
): string {
  return JSON.stringify(
    JoseVerifyApiRequest$outboundSchema.parse(joseVerifyApiRequest),
  );
}
