/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";

export type ServiceUpdateApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  service?: models.ServiceInput | undefined;
};

/** @internal */
export type ServiceUpdateApiRequest$Outbound = {
  serviceId: string;
  service?: models.ServiceInput$Outbound | undefined;
};

/** @internal */
export const ServiceUpdateApiRequest$outboundSchema: z.ZodType<
  ServiceUpdateApiRequest$Outbound,
  z.ZodTypeDef,
  ServiceUpdateApiRequest
> = z.object({
  serviceId: z.string(),
  service: models.ServiceInput$outboundSchema.optional(),
});

export function serviceUpdateApiRequestToJSON(
  serviceUpdateApiRequest: ServiceUpdateApiRequest,
): string {
  return JSON.stringify(
    ServiceUpdateApiRequest$outboundSchema.parse(serviceUpdateApiRequest),
  );
}
