/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type VciDeferredIssueApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciDeferredIssueRequest: models.VciDeferredIssueRequest;
};

/** @internal */
export type VciDeferredIssueApiRequest$Outbound = {
  serviceId: string;
  vci_deferred_issue_request: models.VciDeferredIssueRequest$Outbound;
};

/** @internal */
export const VciDeferredIssueApiRequest$outboundSchema: z.ZodType<
  VciDeferredIssueApiRequest$Outbound,
  z.ZodTypeDef,
  VciDeferredIssueApiRequest
> = z.object({
  serviceId: z.string(),
  vciDeferredIssueRequest: models.VciDeferredIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciDeferredIssueRequest: "vci_deferred_issue_request",
  });
});

export function vciDeferredIssueApiRequestToJSON(
  vciDeferredIssueApiRequest: VciDeferredIssueApiRequest,
): string {
  return JSON.stringify(
    VciDeferredIssueApiRequest$outboundSchema.parse(vciDeferredIssueApiRequest),
  );
}
