/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type VciDeferredParseApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciDeferredParseRequest: models.VciDeferredParseRequest;
};

/** @internal */
export type VciDeferredParseApiRequest$Outbound = {
  serviceId: string;
  vci_deferred_parse_request: models.VciDeferredParseRequest$Outbound;
};

/** @internal */
export const VciDeferredParseApiRequest$outboundSchema: z.ZodType<
  VciDeferredParseApiRequest$Outbound,
  z.ZodTypeDef,
  VciDeferredParseApiRequest
> = z.object({
  serviceId: z.string(),
  vciDeferredParseRequest: models.VciDeferredParseRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciDeferredParseRequest: "vci_deferred_parse_request",
  });
});

export function vciDeferredParseApiRequestToJSON(
  vciDeferredParseApiRequest: VciDeferredParseApiRequest,
): string {
  return JSON.stringify(
    VciDeferredParseApiRequest$outboundSchema.parse(vciDeferredParseApiRequest),
  );
}
