/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciDeferredParseApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciDeferredParseRequest: models.VciDeferredParseRequest;
};

/** @internal */
export const VciDeferredParseApiRequest$inboundSchema: z.ZodType<
  VciDeferredParseApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  vci_deferred_parse_request: models.VciDeferredParseRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "vci_deferred_parse_request": "vciDeferredParseRequest",
  });
});

/** @internal */
export type VciDeferredParseApiRequest$Outbound = {
  serviceId: string;
  vci_deferred_parse_request: models.VciDeferredParseRequest$Outbound;
};

/** @internal */
export const VciDeferredParseApiRequest$outboundSchema: z.ZodType<
  VciDeferredParseApiRequest$Outbound,
  z.ZodTypeDef,
  VciDeferredParseApiRequest
> = z.object({
  serviceId: z.string(),
  vciDeferredParseRequest: models.VciDeferredParseRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciDeferredParseRequest: "vci_deferred_parse_request",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VciDeferredParseApiRequest$ {
  /** @deprecated use `VciDeferredParseApiRequest$inboundSchema` instead. */
  export const inboundSchema = VciDeferredParseApiRequest$inboundSchema;
  /** @deprecated use `VciDeferredParseApiRequest$outboundSchema` instead. */
  export const outboundSchema = VciDeferredParseApiRequest$outboundSchema;
  /** @deprecated use `VciDeferredParseApiRequest$Outbound` instead. */
  export type Outbound = VciDeferredParseApiRequest$Outbound;
}

export function vciDeferredParseApiRequestToJSON(
  vciDeferredParseApiRequest: VciDeferredParseApiRequest,
): string {
  return JSON.stringify(
    VciDeferredParseApiRequest$outboundSchema.parse(vciDeferredParseApiRequest),
  );
}

export function vciDeferredParseApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<VciDeferredParseApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciDeferredParseApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciDeferredParseApiRequest' from JSON`,
  );
}
