/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type VciJwksApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciJwksRequest: models.VciJwksRequest;
};

/** @internal */
export const VciJwksApiRequest$inboundSchema: z.ZodType<
  VciJwksApiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  serviceId: z.string(),
  vci_jwks_request: models.VciJwksRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "vci_jwks_request": "vciJwksRequest",
  });
});

/** @internal */
export type VciJwksApiRequest$Outbound = {
  serviceId: string;
  vci_jwks_request: models.VciJwksRequest$Outbound;
};

/** @internal */
export const VciJwksApiRequest$outboundSchema: z.ZodType<
  VciJwksApiRequest$Outbound,
  z.ZodTypeDef,
  VciJwksApiRequest
> = z.object({
  serviceId: z.string(),
  vciJwksRequest: models.VciJwksRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciJwksRequest: "vci_jwks_request",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VciJwksApiRequest$ {
  /** @deprecated use `VciJwksApiRequest$inboundSchema` instead. */
  export const inboundSchema = VciJwksApiRequest$inboundSchema;
  /** @deprecated use `VciJwksApiRequest$outboundSchema` instead. */
  export const outboundSchema = VciJwksApiRequest$outboundSchema;
  /** @deprecated use `VciJwksApiRequest$Outbound` instead. */
  export type Outbound = VciJwksApiRequest$Outbound;
}

export function vciJwksApiRequestToJSON(
  vciJwksApiRequest: VciJwksApiRequest,
): string {
  return JSON.stringify(
    VciJwksApiRequest$outboundSchema.parse(vciJwksApiRequest),
  );
}

export function vciJwksApiRequestFromJSON(
  jsonString: string,
): SafeParseResult<VciJwksApiRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciJwksApiRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciJwksApiRequest' from JSON`,
  );
}
