/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type VciMetadataApiRequest = {
  /**
   * A service ID.
   */
  serviceId: string;
  vciMetadataRequest: models.VciMetadataRequest;
};

/** @internal */
export type VciMetadataApiRequest$Outbound = {
  serviceId: string;
  vci_metadata_request: models.VciMetadataRequest$Outbound;
};

/** @internal */
export const VciMetadataApiRequest$outboundSchema: z.ZodType<
  VciMetadataApiRequest$Outbound,
  z.ZodTypeDef,
  VciMetadataApiRequest
> = z.object({
  serviceId: z.string(),
  vciMetadataRequest: models.VciMetadataRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vciMetadataRequest: "vci_metadata_request",
  });
});

export function vciMetadataApiRequestToJSON(
  vciMetadataApiRequest: VciMetadataApiRequest,
): string {
  return JSON.stringify(
    VciMetadataApiRequest$outboundSchema.parse(vciMetadataApiRequest),
  );
}
