/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CimdOptions,
  CimdOptions$Outbound,
  CimdOptions$outboundSchema,
} from "./cimdoptions.js";

export type AuthorizationRequest = {
  /**
   * OAuth 2.0 authorization request parameters which are the request parameters that the OAuth 2.0 authorization endpoint of
   *
   * @remarks
   * the authorization server implementation received from the client application.
   *
   * The value of parameters is either (1) the entire query string when the HTTP method of the request from the client application is `GET`
   * or (2) the entire entity body (which is formatted in `application/x-www-form-urlencoded`) when the HTTP method of the request from
   * the client application is `POST`.
   */
  parameters: string;
  /**
   * The arbitrary text to be attached to the ticket that will be issued from the `/auth/authorization`
   *
   * @remarks
   * API.
   *
   * The text can be retrieved later by the `/auth/authorization/ticket/info` API and can be updated
   * by the `/auth/authorization/ticket/update` API.
   *
   * The text will be compressed and encrypted when it is saved in the Authlete database.
   */
  context?: string | undefined;
  /**
   * Options for [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD).
   *
   * @remarks
   *
   * These options allow per-request control over CIMD behavior, taking precedence over service-level configuration when provided.
   */
  cimdOptions?: CimdOptions | undefined;
};

/** @internal */
export type AuthorizationRequest$Outbound = {
  parameters: string;
  context?: string | undefined;
  cimdOptions?: CimdOptions$Outbound | undefined;
};

/** @internal */
export const AuthorizationRequest$outboundSchema: z.ZodType<
  AuthorizationRequest$Outbound,
  z.ZodTypeDef,
  AuthorizationRequest
> = z.object({
  parameters: z.string(),
  context: z.string().optional(),
  cimdOptions: CimdOptions$outboundSchema.optional(),
});

export function authorizationRequestToJSON(
  authorizationRequest: AuthorizationRequest,
): string {
  return JSON.stringify(
    AuthorizationRequest$outboundSchema.parse(authorizationRequest),
  );
}
