/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The reason of the failure of the authorization request.
 *
 * @remarks
 * For more details, see [NO_INTERACTION] in the description of `/auth/authorization` API.
 */
export const AuthorizationFailRequestReason = {
  Unknown: "UNKNOWN",
  NotLoggedIn: "NOT_LOGGED_IN",
  MaxAgeNotSupported: "MAX_AGE_NOT_SUPPORTED",
  ExceedsMaxAge: "EXCEEDS_MAX_AGE",
  DifferentSubject: "DIFFERENT_SUBJECT",
  AcrNotSatisfied: "ACR_NOT_SATISFIED",
  Denied: "DENIED",
  ServerError: "SERVER_ERROR",
  NotAuthenticated: "NOT_AUTHENTICATED",
  AccountSelectionRequired: "ACCOUNT_SELECTION_REQUIRED",
  ConsentRequired: "CONSENT_REQUIRED",
  InteractionRequired: "INTERACTION_REQUIRED",
  InvalidTarget: "INVALID_TARGET",
} as const;
/**
 * The reason of the failure of the authorization request.
 *
 * @remarks
 * For more details, see [NO_INTERACTION] in the description of `/auth/authorization` API.
 */
export type AuthorizationFailRequestReason = ClosedEnum<
  typeof AuthorizationFailRequestReason
>;

export type AuthorizationFailRequest = {
  /**
   * The ticket issued from Authlete `/auth/authorization` API.
   *
   * @remarks
   */
  ticket: string;
  /**
   * The reason of the failure of the authorization request.
   *
   * @remarks
   * For more details, see [NO_INTERACTION] in the description of `/auth/authorization` API.
   */
  reason: AuthorizationFailRequestReason;
  /**
   * The custom description about the authorization failure.
   *
   * @remarks
   */
  description?: string | undefined;
};

/** @internal */
export const AuthorizationFailRequestReason$outboundSchema: z.ZodNativeEnum<
  typeof AuthorizationFailRequestReason
> = z.nativeEnum(AuthorizationFailRequestReason);

/** @internal */
export type AuthorizationFailRequest$Outbound = {
  ticket: string;
  reason: string;
  description?: string | undefined;
};

/** @internal */
export const AuthorizationFailRequest$outboundSchema: z.ZodType<
  AuthorizationFailRequest$Outbound,
  z.ZodTypeDef,
  AuthorizationFailRequest
> = z.object({
  ticket: z.string(),
  reason: AuthorizationFailRequestReason$outboundSchema,
  description: z.string().optional(),
});

export function authorizationFailRequestToJSON(
  authorizationFailRequest: AuthorizationFailRequest,
): string {
  return JSON.stringify(
    AuthorizationFailRequest$outboundSchema.parse(authorizationFailRequest),
  );
}
