/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AuthorizationTicketInfo = {
  /**
   * The arbitrary text attached to the ticket.
   *
   * @remarks
   */
  context?: string | undefined;
};

/** @internal */
export const AuthorizationTicketInfo$inboundSchema: z.ZodType<
  AuthorizationTicketInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  context: z.string().optional(),
});

export function authorizationTicketInfoFromJSON(
  jsonString: string,
): SafeParseResult<AuthorizationTicketInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorizationTicketInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorizationTicketInfo' from JSON`,
  );
}
