/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The result of the `/auth/authorization/ticket/info` API call.
 */
export const AuthorizationTicketInfoResponseAction = {
  Ok: "OK",
  NotFound: "NOT_FOUND",
  CallerError: "CALLER_ERROR",
  AuthleteError: "AUTHLETE_ERROR",
} as const;
/**
 * The result of the `/auth/authorization/ticket/info` API call.
 */
export type AuthorizationTicketInfoResponseAction = ClosedEnum<
  typeof AuthorizationTicketInfoResponseAction
>;

export type AuthorizationTicketInfoResponse = {
  /**
   * Information about the ticket.
   */
  info?: string | undefined;
  /**
   * The result of the `/auth/authorization/ticket/info` API call.
   */
  action?: AuthorizationTicketInfoResponseAction | undefined;
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
};

/** @internal */
export const AuthorizationTicketInfoResponseAction$inboundSchema:
  z.ZodNativeEnum<typeof AuthorizationTicketInfoResponseAction> = z.nativeEnum(
    AuthorizationTicketInfoResponseAction,
  );

/** @internal */
export const AuthorizationTicketInfoResponseAction$outboundSchema:
  z.ZodNativeEnum<typeof AuthorizationTicketInfoResponseAction> =
    AuthorizationTicketInfoResponseAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthorizationTicketInfoResponseAction$ {
  /** @deprecated use `AuthorizationTicketInfoResponseAction$inboundSchema` instead. */
  export const inboundSchema =
    AuthorizationTicketInfoResponseAction$inboundSchema;
  /** @deprecated use `AuthorizationTicketInfoResponseAction$outboundSchema` instead. */
  export const outboundSchema =
    AuthorizationTicketInfoResponseAction$outboundSchema;
}

/** @internal */
export const AuthorizationTicketInfoResponse$inboundSchema: z.ZodType<
  AuthorizationTicketInfoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  info: z.string().optional(),
  action: AuthorizationTicketInfoResponseAction$inboundSchema.optional(),
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
});

/** @internal */
export type AuthorizationTicketInfoResponse$Outbound = {
  info?: string | undefined;
  action?: string | undefined;
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
};

/** @internal */
export const AuthorizationTicketInfoResponse$outboundSchema: z.ZodType<
  AuthorizationTicketInfoResponse$Outbound,
  z.ZodTypeDef,
  AuthorizationTicketInfoResponse
> = z.object({
  info: z.string().optional(),
  action: AuthorizationTicketInfoResponseAction$outboundSchema.optional(),
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuthorizationTicketInfoResponse$ {
  /** @deprecated use `AuthorizationTicketInfoResponse$inboundSchema` instead. */
  export const inboundSchema = AuthorizationTicketInfoResponse$inboundSchema;
  /** @deprecated use `AuthorizationTicketInfoResponse$outboundSchema` instead. */
  export const outboundSchema = AuthorizationTicketInfoResponse$outboundSchema;
  /** @deprecated use `AuthorizationTicketInfoResponse$Outbound` instead. */
  export type Outbound = AuthorizationTicketInfoResponse$Outbound;
}

export function authorizationTicketInfoResponseToJSON(
  authorizationTicketInfoResponse: AuthorizationTicketInfoResponse,
): string {
  return JSON.stringify(
    AuthorizationTicketInfoResponse$outboundSchema.parse(
      authorizationTicketInfoResponse,
    ),
  );
}

export function authorizationTicketInfoResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuthorizationTicketInfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthorizationTicketInfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthorizationTicketInfoResponse' from JSON`,
  );
}
