/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AuthorizationDetailsElement,
  AuthorizationDetailsElement$inboundSchema,
  AuthorizationDetailsElement$Outbound,
  AuthorizationDetailsElement$outboundSchema,
} from "./authorizationdetailselement.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The authorization details. This represents the value of the `authorization_details`
 *
 * @remarks
 * request parameter in the preceding device authorization request which is defined in
 * "OAuth 2.0 Rich Authorization Requests".
 */
export type AuthzDetails = {
  /**
   * Elements of this authorization details.
   *
   * @remarks
   */
  elements?: Array<AuthorizationDetailsElement> | undefined;
};

/** @internal */
export const AuthzDetails$inboundSchema: z.ZodType<
  AuthzDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  elements: z.array(AuthorizationDetailsElement$inboundSchema).optional(),
});
/** @internal */
export type AuthzDetails$Outbound = {
  elements?: Array<AuthorizationDetailsElement$Outbound> | undefined;
};

/** @internal */
export const AuthzDetails$outboundSchema: z.ZodType<
  AuthzDetails$Outbound,
  z.ZodTypeDef,
  AuthzDetails
> = z.object({
  elements: z.array(AuthorizationDetailsElement$outboundSchema).optional(),
});

export function authzDetailsToJSON(authzDetails: AuthzDetails): string {
  return JSON.stringify(AuthzDetails$outboundSchema.parse(authzDetails));
}
export function authzDetailsFromJSON(
  jsonString: string,
): SafeParseResult<AuthzDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuthzDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuthzDetails' from JSON`,
  );
}
