/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The next action that the authorization server implementation should take.
 */
export const BackchannelAuthenticationIssueResponseAction = {
  InternalServerError: "INTERNAL_SERVER_ERROR",
  InvalidTicket: "INVALID_TICKET",
  Ok: "OK",
} as const;
/**
 * The next action that the authorization server implementation should take.
 */
export type BackchannelAuthenticationIssueResponseAction = ClosedEnum<
  typeof BackchannelAuthenticationIssueResponseAction
>;

export type BackchannelAuthenticationIssueResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the authorization server implementation should take.
   */
  action?: BackchannelAuthenticationIssueResponseAction | undefined;
  /**
   * The content that the authorization server implementation is to return to the client
   *
   * @remarks
   * application. Its format varies depending on the value of `action` parameter.
   */
  responseContent?: string | undefined;
  /**
   * The newly issued authentication request ID.
   *
   * @remarks
   */
  authReqId?: string | undefined;
  /**
   * The duration of the issued authentication request ID in seconds.
   *
   * @remarks
   */
  expiresIn?: number | undefined;
  /**
   * The minimum amount of time in seconds that the client must wait for between polling
   *
   * @remarks
   * requests to the token endpoint.
   */
  interval?: number | undefined;
};

/** @internal */
export const BackchannelAuthenticationIssueResponseAction$inboundSchema:
  z.ZodNativeEnum<typeof BackchannelAuthenticationIssueResponseAction> = z
    .nativeEnum(BackchannelAuthenticationIssueResponseAction);

/** @internal */
export const BackchannelAuthenticationIssueResponse$inboundSchema: z.ZodType<
  BackchannelAuthenticationIssueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: BackchannelAuthenticationIssueResponseAction$inboundSchema.optional(),
  responseContent: z.string().optional(),
  authReqId: z.string().optional(),
  expiresIn: z.number().int().optional(),
  interval: z.number().int().optional(),
});

export function backchannelAuthenticationIssueResponseFromJSON(
  jsonString: string,
): SafeParseResult<BackchannelAuthenticationIssueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BackchannelAuthenticationIssueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BackchannelAuthenticationIssueResponse' from JSON`,
  );
}
