/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Values for the `client_registration_types` RP metadata and the
 *
 * @remarks
 *  `client_registration_types_supported` OP metadata that are defined in
 *  [OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
 */
export const ClientRegistrationType = {
  Automatic: "AUTOMATIC",
  Explicit: "EXPLICIT",
} as const;
/**
 * Values for the `client_registration_types` RP metadata and the
 *
 * @remarks
 *  `client_registration_types_supported` OP metadata that are defined in
 *  [OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
 */
export type ClientRegistrationType = ClosedEnum<typeof ClientRegistrationType>;

/** @internal */
export const ClientRegistrationType$inboundSchema: z.ZodNativeEnum<
  typeof ClientRegistrationType
> = z.nativeEnum(ClientRegistrationType);

/** @internal */
export const ClientRegistrationType$outboundSchema: z.ZodNativeEnum<
  typeof ClientRegistrationType
> = ClientRegistrationType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClientRegistrationType$ {
  /** @deprecated use `ClientRegistrationType$inboundSchema` instead. */
  export const inboundSchema = ClientRegistrationType$inboundSchema;
  /** @deprecated use `ClientRegistrationType$outboundSchema` instead. */
  export const outboundSchema = ClientRegistrationType$outboundSchema;
}
