/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientSecretRefreshResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The new client secret.
   *
   * @remarks
   */
  newClientSecret?: string | undefined;
  /**
   * The old client secret.
   *
   * @remarks
   */
  oldClientSecret?: string | undefined;
};

/** @internal */
export const ClientSecretRefreshResponse$inboundSchema: z.ZodType<
  ClientSecretRefreshResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  newClientSecret: z.string().optional(),
  oldClientSecret: z.string().optional(),
});

export function clientSecretRefreshResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientSecretRefreshResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientSecretRefreshResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientSecretRefreshResponse' from JSON`,
  );
}
