/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientFlagUpdateResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode: string;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage: string;
};

/** @internal */
export const ClientFlagUpdateResponse$inboundSchema: z.ZodType<
  ClientFlagUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string(),
  resultMessage: z.string(),
});

export function clientFlagUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientFlagUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientFlagUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientFlagUpdateResponse' from JSON`,
  );
}
