/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientExtensionRequestableScopesUpdateResponse = {
  requestableScopes?: Array<string> | undefined;
};

/** @internal */
export const ClientExtensionRequestableScopesUpdateResponse$inboundSchema:
  z.ZodType<
    ClientExtensionRequestableScopesUpdateResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    requestableScopes: z.array(z.string()).optional(),
  });

export function clientExtensionRequestableScopesUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ClientExtensionRequestableScopesUpdateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ClientExtensionRequestableScopesUpdateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ClientExtensionRequestableScopesUpdateResponse' from JSON`,
  );
}
