/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ClientLimited, ClientLimited$inboundSchema } from "./clientlimited.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientAuthorizationGetListResponse = {
  /**
   * Start index of search results (inclusive).
   *
   * @remarks
   */
  start?: number | undefined;
  /**
   * End index of search results (exclusive).
   *
   * @remarks
   */
  end?: number | undefined;
  /**
   * Unique ID of a client developer.
   *
   * @remarks
   */
  developer?: string | undefined;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject?: string | undefined;
  /**
   * Unique ID of a client developer.
   *
   * @remarks
   */
  totalCount?: number | undefined;
  /**
   * An array of clients.
   *
   * @remarks
   */
  clients?: Array<ClientLimited> | undefined;
};

/** @internal */
export const ClientAuthorizationGetListResponse$inboundSchema: z.ZodType<
  ClientAuthorizationGetListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  developer: z.string().optional(),
  subject: z.string().optional(),
  totalCount: z.number().int().optional(),
  clients: z.array(ClientLimited$inboundSchema).optional(),
});

export function clientAuthorizationGetListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientAuthorizationGetListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ClientAuthorizationGetListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientAuthorizationGetListResponse' from JSON`,
  );
}
