/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientGrantedScopesDeleteResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
};

/** @internal */
export const ClientGrantedScopesDeleteResponse$inboundSchema: z.ZodType<
  ClientGrantedScopesDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
});

export function clientGrantedScopesDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGrantedScopesDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientGrantedScopesDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGrantedScopesDeleteResponse' from JSON`,
  );
}
