/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ClientGrantedScopesDeleteResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
};

/** @internal */
export const ClientGrantedScopesDeleteResponse$inboundSchema: z.ZodType<
  ClientGrantedScopesDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
});

/** @internal */
export type ClientGrantedScopesDeleteResponse$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
};

/** @internal */
export const ClientGrantedScopesDeleteResponse$outboundSchema: z.ZodType<
  ClientGrantedScopesDeleteResponse$Outbound,
  z.ZodTypeDef,
  ClientGrantedScopesDeleteResponse
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClientGrantedScopesDeleteResponse$ {
  /** @deprecated use `ClientGrantedScopesDeleteResponse$inboundSchema` instead. */
  export const inboundSchema = ClientGrantedScopesDeleteResponse$inboundSchema;
  /** @deprecated use `ClientGrantedScopesDeleteResponse$outboundSchema` instead. */
  export const outboundSchema =
    ClientGrantedScopesDeleteResponse$outboundSchema;
  /** @deprecated use `ClientGrantedScopesDeleteResponse$Outbound` instead. */
  export type Outbound = ClientGrantedScopesDeleteResponse$Outbound;
}

export function clientGrantedScopesDeleteResponseToJSON(
  clientGrantedScopesDeleteResponse: ClientGrantedScopesDeleteResponse,
): string {
  return JSON.stringify(
    ClientGrantedScopesDeleteResponse$outboundSchema.parse(
      clientGrantedScopesDeleteResponse,
    ),
  );
}

export function clientGrantedScopesDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<ClientGrantedScopesDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientGrantedScopesDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientGrantedScopesDeleteResponse' from JSON`,
  );
}
