/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const DeliveryMode = {
  Ping: "PING",
  Poll: "POLL",
  Push: "PUSH",
} as const;
export type DeliveryMode = ClosedEnum<typeof DeliveryMode>;

/** @internal */
export const DeliveryMode$inboundSchema: z.ZodNativeEnum<typeof DeliveryMode> =
  z.nativeEnum(DeliveryMode);

/** @internal */
export const DeliveryMode$outboundSchema: z.ZodNativeEnum<typeof DeliveryMode> =
  DeliveryMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeliveryMode$ {
  /** @deprecated use `DeliveryMode$inboundSchema` instead. */
  export const inboundSchema = DeliveryMode$inboundSchema;
  /** @deprecated use `DeliveryMode$outboundSchema` instead. */
  export const outboundSchema = DeliveryMode$outboundSchema;
}
