/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The next action that the authorization server implementation should take.
 *
 * @remarks
 */
export const DeviceCompleteResponseAction = {
  ServerError: "SERVER_ERROR",
  UserCodeNotExist: "USER_CODE_NOT_EXIST",
  UserCodeExpired: "USER_CODE_EXPIRED",
  InvalidRequest: "INVALID_REQUEST",
  Success: "SUCCESS",
} as const;
/**
 * The next action that the authorization server implementation should take.
 *
 * @remarks
 */
export type DeviceCompleteResponseAction = ClosedEnum<
  typeof DeviceCompleteResponseAction
>;

export type DeviceCompleteResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the authorization server implementation should take.
   *
   * @remarks
   */
  action?: DeviceCompleteResponseAction | undefined;
};

/** @internal */
export const DeviceCompleteResponseAction$inboundSchema: z.ZodNativeEnum<
  typeof DeviceCompleteResponseAction
> = z.nativeEnum(DeviceCompleteResponseAction);

/** @internal */
export const DeviceCompleteResponse$inboundSchema: z.ZodType<
  DeviceCompleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: DeviceCompleteResponseAction$inboundSchema.optional(),
});

export function deviceCompleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeviceCompleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeviceCompleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeviceCompleteResponse' from JSON`,
  );
}
