/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FapiMode = {
  Fapi1Advanced: "FAPI1_ADVANCED",
  Fapi1Baseline: "FAPI1_BASELINE",
  Fapi2MessageSigningAuthReq: "FAPI2_MESSAGE_SIGNING_AUTH_REQ",
  Fapi2MessageSigningAuthRes: "FAPI2_MESSAGE_SIGNING_AUTH_RES",
  Fapi2MessageSigningIntrospectionRes:
    "FAPI2_MESSAGE_SIGNING_INTROSPECTION_RES",
  Fapi2Security: "FAPI2_SECURITY",
} as const;
export type FapiMode = ClosedEnum<typeof FapiMode>;

/** @internal */
export const FapiMode$inboundSchema: z.ZodNativeEnum<typeof FapiMode> = z
  .nativeEnum(FapiMode);

/** @internal */
export const FapiMode$outboundSchema: z.ZodNativeEnum<typeof FapiMode> =
  FapiMode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FapiMode$ {
  /** @deprecated use `FapiMode$inboundSchema` instead. */
  export const inboundSchema = FapiMode$inboundSchema;
  /** @deprecated use `FapiMode$outboundSchema` instead. */
  export const outboundSchema = FapiMode$outboundSchema;
}
