/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Client, Client$inboundSchema } from "./client.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The next action that the authorization server implementation should take.
 */
export const FederationRegistrationResponseAction = {
  Ok: "OK",
  BadRequest: "BAD_REQUEST",
  NotFound: "NOT_FOUND",
  InternalServerError: "INTERNAL_SERVER_ERROR",
} as const;
/**
 * The next action that the authorization server implementation should take.
 */
export type FederationRegistrationResponseAction = ClosedEnum<
  typeof FederationRegistrationResponseAction
>;

export type FederationRegistrationResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the authorization server implementation should take.
   */
  action?: FederationRegistrationResponseAction | undefined;
  /**
   * The content that the authorization server implementation can use as the value of `WWW-Authenticate`
   *
   * @remarks
   * header on errors.
   */
  responseContent?: string | undefined;
  client?: Client | undefined;
};

/** @internal */
export const FederationRegistrationResponseAction$inboundSchema:
  z.ZodNativeEnum<typeof FederationRegistrationResponseAction> = z.nativeEnum(
    FederationRegistrationResponseAction,
  );

/** @internal */
export const FederationRegistrationResponse$inboundSchema: z.ZodType<
  FederationRegistrationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: FederationRegistrationResponseAction$inboundSchema.optional(),
  responseContent: z.string().optional(),
  client: Client$inboundSchema.optional(),
});

export function federationRegistrationResponseFromJSON(
  jsonString: string,
): SafeParseResult<FederationRegistrationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FederationRegistrationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FederationRegistrationResponse' from JSON`,
  );
}
