/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FederationRegistrationRequest = {
  /**
   * The entity configuration of a relying party.
   *
   * @remarks
   */
  entityConfiguration?: string | undefined;
  /**
   * The trust chain of a relying party.
   *
   * @remarks
   */
  trustChain?: string | undefined;
};

/** @internal */
export const FederationRegistrationRequest$inboundSchema: z.ZodType<
  FederationRegistrationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  entityConfiguration: z.string().optional(),
  trustChain: z.string().optional(),
});

/** @internal */
export type FederationRegistrationRequest$Outbound = {
  entityConfiguration?: string | undefined;
  trustChain?: string | undefined;
};

/** @internal */
export const FederationRegistrationRequest$outboundSchema: z.ZodType<
  FederationRegistrationRequest$Outbound,
  z.ZodTypeDef,
  FederationRegistrationRequest
> = z.object({
  entityConfiguration: z.string().optional(),
  trustChain: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FederationRegistrationRequest$ {
  /** @deprecated use `FederationRegistrationRequest$inboundSchema` instead. */
  export const inboundSchema = FederationRegistrationRequest$inboundSchema;
  /** @deprecated use `FederationRegistrationRequest$outboundSchema` instead. */
  export const outboundSchema = FederationRegistrationRequest$outboundSchema;
  /** @deprecated use `FederationRegistrationRequest$Outbound` instead. */
  export type Outbound = FederationRegistrationRequest$Outbound;
}

export function federationRegistrationRequestToJSON(
  federationRegistrationRequest: FederationRegistrationRequest,
): string {
  return JSON.stringify(
    FederationRegistrationRequest$outboundSchema.parse(
      federationRegistrationRequest,
    ),
  );
}

export function federationRegistrationRequestFromJSON(
  jsonString: string,
): SafeParseResult<FederationRegistrationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FederationRegistrationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FederationRegistrationRequest' from JSON`,
  );
}
