/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GrantScope = {
  /**
   * Space-delimited scopes.
   *
   * @remarks
   */
  scope?: string | undefined;
  /**
   * List of resource indicators.
   *
   * @remarks
   */
  resource?: Array<string> | undefined;
};

/** @internal */
export const GrantScope$inboundSchema: z.ZodType<
  GrantScope,
  z.ZodTypeDef,
  unknown
> = z.object({
  scope: z.string().optional(),
  resource: z.array(z.string()).optional(),
});

export function grantScopeFromJSON(
  jsonString: string,
): SafeParseResult<GrantScope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GrantScope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GrantScope' from JSON`,
  );
}
