/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export const GrantManagementAction = {
  Create: "CREATE",
  Query: "QUERY",
  Replace: "REPLACE",
  Revoke: "REVOKE",
  Merge: "MERGE",
} as const;
/**
 * The grant management action of the device authorization request.
 *
 * @remarks
 *
 * The `grant_management_action` request parameter is defined in
 * [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
 */
export type GrantManagementAction = ClosedEnum<typeof GrantManagementAction>;

/** @internal */
export const GrantManagementAction$inboundSchema: z.ZodNativeEnum<
  typeof GrantManagementAction
> = z.nativeEnum(GrantManagementAction);

/** @internal */
export const GrantManagementAction$outboundSchema: z.ZodNativeEnum<
  typeof GrantManagementAction
> = GrantManagementAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GrantManagementAction$ {
  /** @deprecated use `GrantManagementAction$inboundSchema` instead. */
  export const inboundSchema = GrantManagementAction$inboundSchema;
  /** @deprecated use `GrantManagementAction$outboundSchema` instead. */
  export const outboundSchema = GrantManagementAction$outboundSchema;
}
