/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Hsk,
  Hsk$inboundSchema,
  Hsk$Outbound,
  Hsk$outboundSchema,
} from "./hsk.js";

/**
 * Result of the API call.
 */
export const HskCreateResponseAction = {
  Success: "SUCCESS",
  InvalidRequest: "INVALID_REQUEST",
  NotFound: "NOT_FOUND",
  ServerError: "SERVER_ERROR",
} as const;
/**
 * Result of the API call.
 */
export type HskCreateResponseAction = ClosedEnum<
  typeof HskCreateResponseAction
>;

export type HskCreateResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * Result of the API call.
   */
  action?: HskCreateResponseAction | undefined;
  /**
   * Holds information about a key managed in an HSM (Hardware Security Module)
   *
   * @remarks
   */
  hsk?: Hsk | undefined;
};

/** @internal */
export const HskCreateResponseAction$inboundSchema: z.ZodNativeEnum<
  typeof HskCreateResponseAction
> = z.nativeEnum(HskCreateResponseAction);

/** @internal */
export const HskCreateResponseAction$outboundSchema: z.ZodNativeEnum<
  typeof HskCreateResponseAction
> = HskCreateResponseAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HskCreateResponseAction$ {
  /** @deprecated use `HskCreateResponseAction$inboundSchema` instead. */
  export const inboundSchema = HskCreateResponseAction$inboundSchema;
  /** @deprecated use `HskCreateResponseAction$outboundSchema` instead. */
  export const outboundSchema = HskCreateResponseAction$outboundSchema;
}

/** @internal */
export const HskCreateResponse$inboundSchema: z.ZodType<
  HskCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: HskCreateResponseAction$inboundSchema.optional(),
  hsk: Hsk$inboundSchema.optional(),
});

/** @internal */
export type HskCreateResponse$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
  action?: string | undefined;
  hsk?: Hsk$Outbound | undefined;
};

/** @internal */
export const HskCreateResponse$outboundSchema: z.ZodType<
  HskCreateResponse$Outbound,
  z.ZodTypeDef,
  HskCreateResponse
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: HskCreateResponseAction$outboundSchema.optional(),
  hsk: Hsk$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HskCreateResponse$ {
  /** @deprecated use `HskCreateResponse$inboundSchema` instead. */
  export const inboundSchema = HskCreateResponse$inboundSchema;
  /** @deprecated use `HskCreateResponse$outboundSchema` instead. */
  export const outboundSchema = HskCreateResponse$outboundSchema;
  /** @deprecated use `HskCreateResponse$Outbound` instead. */
  export type Outbound = HskCreateResponse$Outbound;
}

export function hskCreateResponseToJSON(
  hskCreateResponse: HskCreateResponse,
): string {
  return JSON.stringify(
    HskCreateResponse$outboundSchema.parse(hskCreateResponse),
  );
}

export function hskCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<HskCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskCreateResponse' from JSON`,
  );
}
