/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Hsk, Hsk$inboundSchema } from "./hsk.js";

/**
 * Result of the API call
 */
export const HskDeleteResponseAction = {
  Success: "SUCCESS",
  InvalidRequest: "INVALID_REQUEST",
  NotFound: "NOT_FOUND",
  ServerError: "SERVER_ERROR",
} as const;
/**
 * Result of the API call
 */
export type HskDeleteResponseAction = ClosedEnum<
  typeof HskDeleteResponseAction
>;

export type HskDeleteResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * Result of the API call
   */
  action?: HskDeleteResponseAction | undefined;
  /**
   * Holds information about a key managed in an HSM (Hardware Security Module)
   *
   * @remarks
   */
  hsk?: Hsk | undefined;
};

/** @internal */
export const HskDeleteResponseAction$inboundSchema: z.ZodNativeEnum<
  typeof HskDeleteResponseAction
> = z.nativeEnum(HskDeleteResponseAction);

/** @internal */
export const HskDeleteResponse$inboundSchema: z.ZodType<
  HskDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: HskDeleteResponseAction$inboundSchema.optional(),
  hsk: Hsk$inboundSchema.optional(),
});

export function hskDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<HskDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HskDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HskDeleteResponse' from JSON`,
  );
}
