/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The next action that the implementation of the token endpoint should take.
 */
export const IdtokenReissueResponseAction = {
  Ok: "OK",
  InternalServerError: "INTERNAL_SERVER_ERROR",
  CallerError: "CALLER_ERROR",
} as const;
/**
 * The next action that the implementation of the token endpoint should take.
 */
export type IdtokenReissueResponseAction = ClosedEnum<
  typeof IdtokenReissueResponseAction
>;

export type IdtokenReissueResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the implementation of the token endpoint should take.
   */
  action?: IdtokenReissueResponseAction | undefined;
  /**
   * The response content that can be used as the message body of the token response that should
   *
   * @remarks
   * be returned from the token endpoint.
   */
  responseContent?: string | undefined;
  /**
   * The reissued ID token
   *
   * @remarks
   */
  idToken?: string | undefined;
};

/** @internal */
export const IdtokenReissueResponseAction$inboundSchema: z.ZodNativeEnum<
  typeof IdtokenReissueResponseAction
> = z.nativeEnum(IdtokenReissueResponseAction);

/** @internal */
export const IdtokenReissueResponse$inboundSchema: z.ZodType<
  IdtokenReissueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: IdtokenReissueResponseAction$inboundSchema.optional(),
  responseContent: z.string().optional(),
  idToken: z.string().optional(),
});

export function idtokenReissueResponseFromJSON(
  jsonString: string,
): SafeParseResult<IdtokenReissueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IdtokenReissueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IdtokenReissueResponse' from JSON`,
  );
}
