/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InfoResponse = {
  /**
   * The server version.
   */
  version: string;
  /**
   * the features that the server supports.
   */
  features: Array<string>;
};

/** @internal */
export const InfoResponse$inboundSchema: z.ZodType<
  InfoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  version: z.string(),
  features: z.array(z.string()),
});

/** @internal */
export type InfoResponse$Outbound = {
  version: string;
  features: Array<string>;
};

/** @internal */
export const InfoResponse$outboundSchema: z.ZodType<
  InfoResponse$Outbound,
  z.ZodTypeDef,
  InfoResponse
> = z.object({
  version: z.string(),
  features: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InfoResponse$ {
  /** @deprecated use `InfoResponse$inboundSchema` instead. */
  export const inboundSchema = InfoResponse$inboundSchema;
  /** @deprecated use `InfoResponse$outboundSchema` instead. */
  export const outboundSchema = InfoResponse$outboundSchema;
  /** @deprecated use `InfoResponse$Outbound` instead. */
  export type Outbound = InfoResponse$Outbound;
}

export function infoResponseToJSON(infoResponse: InfoResponse): string {
  return JSON.stringify(InfoResponse$outboundSchema.parse(infoResponse));
}

export function infoResponseFromJSON(
  jsonString: string,
): SafeParseResult<InfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoResponse' from JSON`,
  );
}
