/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ResponseType = {
  None: "NONE",
  Code: "CODE",
  Token: "TOKEN",
  IdToken: "ID_TOKEN",
  CodeToken: "CODE_TOKEN",
  CodeIdToken: "CODE_ID_TOKEN",
  IdTokenToken: "ID_TOKEN_TOKEN",
  CodeIdTokenToken: "CODE_ID_TOKEN_TOKEN",
} as const;
export type ResponseType = ClosedEnum<typeof ResponseType>;

/** @internal */
export const ResponseType$inboundSchema: z.ZodNativeEnum<typeof ResponseType> =
  z.nativeEnum(ResponseType);

/** @internal */
export const ResponseType$outboundSchema: z.ZodNativeEnum<typeof ResponseType> =
  ResponseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseType$ {
  /** @deprecated use `ResponseType$inboundSchema` instead. */
  export const inboundSchema = ResponseType$inboundSchema;
  /** @deprecated use `ResponseType$outboundSchema` instead. */
  export const outboundSchema = ResponseType$outboundSchema;
}
