/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ServiceJwksGetResponse = {
  /**
   * An array of [JWK](https://datatracker.ietf.org/doc/html/rfc7517)s.
   */
  keys?: Array<{ [k: string]: any }> | undefined;
};

/** @internal */
export const ServiceJwksGetResponse$inboundSchema: z.ZodType<
  ServiceJwksGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  keys: z.array(z.record(z.any())).optional(),
});

export function serviceJwksGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServiceJwksGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServiceJwksGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServiceJwksGetResponse' from JSON`,
  );
}
