/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The subject type that the client application requests. Details about the subject type are described in
 *
 * @remarks
 * [OpenID Connect Core 1.0, 8. Subjct Identifier Types](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes).
 *
 * This property corresponds to `subject_type` in
 * [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
 */
export const SubjectType = {
  Public: "PUBLIC",
  Pairwise: "PAIRWISE",
} as const;
/**
 * The subject type that the client application requests. Details about the subject type are described in
 *
 * @remarks
 * [OpenID Connect Core 1.0, 8. Subjct Identifier Types](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes).
 *
 * This property corresponds to `subject_type` in
 * [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
 */
export type SubjectType = ClosedEnum<typeof SubjectType>;

/** @internal */
export const SubjectType$inboundSchema: z.ZodNativeEnum<typeof SubjectType> = z
  .nativeEnum(SubjectType);

/** @internal */
export const SubjectType$outboundSchema: z.ZodNativeEnum<typeof SubjectType> =
  SubjectType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubjectType$ {
  /** @deprecated use `SubjectType$inboundSchema` instead. */
  export const inboundSchema = SubjectType$inboundSchema;
  /** @deprecated use `SubjectType$outboundSchema` instead. */
  export const outboundSchema = SubjectType$outboundSchema;
}
