/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The kind of batch operation.
 */
export const BatchKind = {
  Create: "CREATE",
} as const;
/**
 * The kind of batch operation.
 */
export type BatchKind = ClosedEnum<typeof BatchKind>;

/**
 * The result of the batch operation.
 */
export const TokenBatchStatusResult = {
  Succeeded: "SUCCEEDED",
  Failed: "FAILED",
} as const;
/**
 * The result of the batch operation.
 */
export type TokenBatchStatusResult = ClosedEnum<typeof TokenBatchStatusResult>;

/**
 * Status of a token batch operation.
 *
 * @remarks
 */
export type TokenBatchStatus = {
  /**
   * The kind of batch operation.
   */
  batchKind?: BatchKind | undefined;
  /**
   * The request ID.
   */
  requestId?: string | undefined;
  /**
   * The result of the batch operation.
   */
  result?: TokenBatchStatusResult | undefined;
  /**
   * The error code if the operation failed.
   */
  errorCode?: string | undefined;
  /**
   * The error description if the operation failed.
   */
  errorDescription?: string | undefined;
  /**
   * The number of tokens processed.
   */
  tokenCount?: number | undefined;
  /**
   * The time at which the batch operation was created (timestamp).
   */
  createdAt?: number | undefined;
  /**
   * The time at which the batch operation was last modified (timestamp).
   */
  modifiedAt?: number | undefined;
};

/** @internal */
export const BatchKind$inboundSchema: z.ZodNativeEnum<typeof BatchKind> = z
  .nativeEnum(BatchKind);

/** @internal */
export const TokenBatchStatusResult$inboundSchema: z.ZodNativeEnum<
  typeof TokenBatchStatusResult
> = z.nativeEnum(TokenBatchStatusResult);

/** @internal */
export const TokenBatchStatus$inboundSchema: z.ZodType<
  TokenBatchStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  batchKind: BatchKind$inboundSchema.optional(),
  requestId: z.string().optional(),
  result: TokenBatchStatusResult$inboundSchema.optional(),
  errorCode: z.string().optional(),
  errorDescription: z.string().optional(),
  tokenCount: z.number().int().optional(),
  createdAt: z.number().int().optional(),
  modifiedAt: z.number().int().optional(),
});

export function tokenBatchStatusFromJSON(
  jsonString: string,
): SafeParseResult<TokenBatchStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenBatchStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenBatchStatus' from JSON`,
  );
}
