/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AuthzDetails,
  AuthzDetails$inboundSchema,
  AuthzDetails$Outbound,
  AuthzDetails$outboundSchema,
} from "./authzdetails.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  Pair,
  Pair$inboundSchema,
  Pair$Outbound,
  Pair$outboundSchema,
} from "./pair.js";
import {
  Property,
  Property$inboundSchema,
  Property$Outbound,
  Property$outboundSchema,
} from "./property.js";

/**
 * The next action that the authorization server implementation should take.
 */
export const TokenIssueResponseAction = {
  InternalServerError: "INTERNAL_SERVER_ERROR",
  Ok: "OK",
} as const;
/**
 * The next action that the authorization server implementation should take.
 */
export type TokenIssueResponseAction = ClosedEnum<
  typeof TokenIssueResponseAction
>;

export type TokenIssueResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The next action that the authorization server implementation should take.
   */
  action?: TokenIssueResponseAction | undefined;
  /**
   * The content that the authorization server implementation is to return to the client application.
   *
   * @remarks
   * Its format is JSON.
   */
  responseContent?: string | undefined;
  /**
   * The newly issued access token. This parameter is a non-null value only when the value of `action` parameter is `OK`.
   */
  accessToken?: string | undefined;
  /**
   * The datetime at which the newly issued access token will expire.
   *
   * @remarks
   * The value is represented in milliseconds since the Unix epoch (1970-01-01).
   */
  accessTokenExpiresAt?: number | undefined;
  /**
   * The duration of the newly issued access token in seconds.
   */
  accessTokenDuration?: number | undefined;
  /**
   * The refresh token. This parameter is a non-null value only when `action` is `OK` and the service supports the refresh token flow.
   *
   * @remarks
   * If `refreshTokenKept` is set to `false`, a new refresh token is issued and the old refresh token used in the refresh token flow
   * is invalidated. On the contrary, if `refreshTokenKept` is set to `true`, the refresh token itself is not refreshed.
   */
  refreshToken?: string | undefined;
  /**
   * The datetime at which the newly issued refresh token will expire.
   *
   * @remarks
   * The value is represented in milliseconds since the Unix epoch (1970-01-01).
   */
  refreshTokenExpiresAt?: number | undefined;
  /**
   * The duration of the newly issued refresh token in seconds.
   */
  refreshTokenDuration?: number | undefined;
  /**
   * The client ID.
   */
  clientId?: number | undefined;
  /**
   * The client ID alias. If the client did not have an alias, this parameter is `null`.
   *
   * @remarks
   */
  clientIdAlias?: string | undefined;
  /**
   * The flag which indicates whether the client ID alias was used when the token request was made.
   *
   * @remarks
   * `true` if the client ID alias was used when the token request was made.
   */
  clientIdAliasUsed?: boolean | undefined;
  /**
   * The subject (= resource owner's ID) of the access token.
   *
   * @remarks
   * Even if an access token has been issued by calling `/api/auth/token` API, this parameter is `null` if the flow of the token request was
   * [Client Credentials Flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4) (`grant_type=client_credentials`) because it means
   * the access token is not associated with any specific end-user.
   */
  subject?: string | undefined;
  /**
   * The scopes covered by the access token.
   */
  scopes?: Array<string> | undefined;
  /**
   * The extra properties associated with the access token.
   *
   * @remarks
   * This parameter is `null` when no extra property is associated with the issued access token.
   */
  properties?: Array<Property> | undefined;
  /**
   * The newly issued access token in JWT format. If the authorization server is configured to issue JWT-based access tokens
   *
   * @remarks
   * (= if the service's `accessTokenSignAlg` value is a non-null value), a JWT-based access token is issued along with the
   * original random-string one.
   */
  jwtAccessToken?: string | undefined;
  /**
   * The target resources of the access token being issued. See "Resource Indicators for OAuth 2.0" for details.
   *
   * @remarks
   */
  accessTokenResources?: Array<string> | undefined;
  /**
   * The authorization details. This represents the value of the `authorization_details`
   *
   * @remarks
   * request parameter in the preceding device authorization request which is defined in
   * "OAuth 2.0 Rich Authorization Requests".
   */
  authorizationDetails?: AuthzDetails | undefined;
  /**
   * The attributes of this service that the client application belongs to.
   *
   * @remarks
   */
  serviceAttributes?: Array<Pair> | undefined;
  /**
   * The attributes of the client.
   *
   * @remarks
   */
  clientAttributes?: Array<Pair> | undefined;
  /**
   * The entity ID of the client.
   *
   * @remarks
   */
  clientEntityId?: string | undefined;
  /**
   * Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
   *
   * @remarks
   */
  clientEntityIdUsed?: boolean | undefined;
  /**
   * The scopes associated with the refresh token. May be null.
   *
   * @remarks
   */
  refreshTokenScopes?: Array<string> | undefined;
};

/** @internal */
export const TokenIssueResponseAction$inboundSchema: z.ZodNativeEnum<
  typeof TokenIssueResponseAction
> = z.nativeEnum(TokenIssueResponseAction);

/** @internal */
export const TokenIssueResponseAction$outboundSchema: z.ZodNativeEnum<
  typeof TokenIssueResponseAction
> = TokenIssueResponseAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TokenIssueResponseAction$ {
  /** @deprecated use `TokenIssueResponseAction$inboundSchema` instead. */
  export const inboundSchema = TokenIssueResponseAction$inboundSchema;
  /** @deprecated use `TokenIssueResponseAction$outboundSchema` instead. */
  export const outboundSchema = TokenIssueResponseAction$outboundSchema;
}

/** @internal */
export const TokenIssueResponse$inboundSchema: z.ZodType<
  TokenIssueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: TokenIssueResponseAction$inboundSchema.optional(),
  responseContent: z.string().optional(),
  accessToken: z.string().optional(),
  accessTokenExpiresAt: z.number().int().optional(),
  accessTokenDuration: z.number().int().optional(),
  refreshToken: z.string().optional(),
  refreshTokenExpiresAt: z.number().int().optional(),
  refreshTokenDuration: z.number().int().optional(),
  clientId: z.number().int().optional(),
  clientIdAlias: z.string().optional(),
  clientIdAliasUsed: z.boolean().optional(),
  subject: z.string().optional(),
  scopes: z.array(z.string()).optional(),
  properties: z.array(Property$inboundSchema).optional(),
  jwtAccessToken: z.string().optional(),
  accessTokenResources: z.array(z.string()).optional(),
  authorizationDetails: AuthzDetails$inboundSchema.optional(),
  serviceAttributes: z.array(Pair$inboundSchema).optional(),
  clientAttributes: z.array(Pair$inboundSchema).optional(),
  clientEntityId: z.string().optional(),
  clientEntityIdUsed: z.boolean().optional(),
  refreshTokenScopes: z.array(z.string()).optional(),
});

/** @internal */
export type TokenIssueResponse$Outbound = {
  resultCode?: string | undefined;
  resultMessage?: string | undefined;
  action?: string | undefined;
  responseContent?: string | undefined;
  accessToken?: string | undefined;
  accessTokenExpiresAt?: number | undefined;
  accessTokenDuration?: number | undefined;
  refreshToken?: string | undefined;
  refreshTokenExpiresAt?: number | undefined;
  refreshTokenDuration?: number | undefined;
  clientId?: number | undefined;
  clientIdAlias?: string | undefined;
  clientIdAliasUsed?: boolean | undefined;
  subject?: string | undefined;
  scopes?: Array<string> | undefined;
  properties?: Array<Property$Outbound> | undefined;
  jwtAccessToken?: string | undefined;
  accessTokenResources?: Array<string> | undefined;
  authorizationDetails?: AuthzDetails$Outbound | undefined;
  serviceAttributes?: Array<Pair$Outbound> | undefined;
  clientAttributes?: Array<Pair$Outbound> | undefined;
  clientEntityId?: string | undefined;
  clientEntityIdUsed?: boolean | undefined;
  refreshTokenScopes?: Array<string> | undefined;
};

/** @internal */
export const TokenIssueResponse$outboundSchema: z.ZodType<
  TokenIssueResponse$Outbound,
  z.ZodTypeDef,
  TokenIssueResponse
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: TokenIssueResponseAction$outboundSchema.optional(),
  responseContent: z.string().optional(),
  accessToken: z.string().optional(),
  accessTokenExpiresAt: z.number().int().optional(),
  accessTokenDuration: z.number().int().optional(),
  refreshToken: z.string().optional(),
  refreshTokenExpiresAt: z.number().int().optional(),
  refreshTokenDuration: z.number().int().optional(),
  clientId: z.number().int().optional(),
  clientIdAlias: z.string().optional(),
  clientIdAliasUsed: z.boolean().optional(),
  subject: z.string().optional(),
  scopes: z.array(z.string()).optional(),
  properties: z.array(Property$outboundSchema).optional(),
  jwtAccessToken: z.string().optional(),
  accessTokenResources: z.array(z.string()).optional(),
  authorizationDetails: AuthzDetails$outboundSchema.optional(),
  serviceAttributes: z.array(Pair$outboundSchema).optional(),
  clientAttributes: z.array(Pair$outboundSchema).optional(),
  clientEntityId: z.string().optional(),
  clientEntityIdUsed: z.boolean().optional(),
  refreshTokenScopes: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TokenIssueResponse$ {
  /** @deprecated use `TokenIssueResponse$inboundSchema` instead. */
  export const inboundSchema = TokenIssueResponse$inboundSchema;
  /** @deprecated use `TokenIssueResponse$outboundSchema` instead. */
  export const outboundSchema = TokenIssueResponse$outboundSchema;
  /** @deprecated use `TokenIssueResponse$Outbound` instead. */
  export type Outbound = TokenIssueResponse$Outbound;
}

export function tokenIssueResponseToJSON(
  tokenIssueResponse: TokenIssueResponse,
): string {
  return JSON.stringify(
    TokenIssueResponse$outboundSchema.parse(tokenIssueResponse),
  );
}

export function tokenIssueResponseFromJSON(
  jsonString: string,
): SafeParseResult<TokenIssueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenIssueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenIssueResponse' from JSON`,
  );
}
