/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccessToken,
  AccessToken$inboundSchema,
  AccessToken$Outbound,
  AccessToken$outboundSchema,
} from "./accesstoken.js";
import {
  ClientLimited,
  ClientLimited$inboundSchema,
  ClientLimited$Outbound,
  ClientLimited$outboundSchema,
} from "./clientlimited.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TokenGetListResponse = {
  /**
   * Start index of search results (inclusive).
   *
   * @remarks
   */
  start?: number | undefined;
  /**
   * End index of search results (exclusive).
   *
   * @remarks
   */
  end?: number | undefined;
  /**
   * Unique ID of a client developer.
   *
   * @remarks
   */
  totalCount?: number | undefined;
  client?: ClientLimited | undefined;
  /**
   * Unique user ID of an end-user.
   *
   * @remarks
   */
  subject?: string | undefined;
  /**
   * An array of access tokens.
   *
   * @remarks
   */
  accessTokens?: Array<AccessToken> | undefined;
};

/** @internal */
export const TokenGetListResponse$inboundSchema: z.ZodType<
  TokenGetListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  totalCount: z.number().int().optional(),
  client: ClientLimited$inboundSchema.optional(),
  subject: z.string().optional(),
  accessTokens: z.array(AccessToken$inboundSchema).optional(),
});

/** @internal */
export type TokenGetListResponse$Outbound = {
  start?: number | undefined;
  end?: number | undefined;
  totalCount?: number | undefined;
  client?: ClientLimited$Outbound | undefined;
  subject?: string | undefined;
  accessTokens?: Array<AccessToken$Outbound> | undefined;
};

/** @internal */
export const TokenGetListResponse$outboundSchema: z.ZodType<
  TokenGetListResponse$Outbound,
  z.ZodTypeDef,
  TokenGetListResponse
> = z.object({
  start: z.number().int().optional(),
  end: z.number().int().optional(),
  totalCount: z.number().int().optional(),
  client: ClientLimited$outboundSchema.optional(),
  subject: z.string().optional(),
  accessTokens: z.array(AccessToken$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TokenGetListResponse$ {
  /** @deprecated use `TokenGetListResponse$inboundSchema` instead. */
  export const inboundSchema = TokenGetListResponse$inboundSchema;
  /** @deprecated use `TokenGetListResponse$outboundSchema` instead. */
  export const outboundSchema = TokenGetListResponse$outboundSchema;
  /** @deprecated use `TokenGetListResponse$Outbound` instead. */
  export type Outbound = TokenGetListResponse$Outbound;
}

export function tokenGetListResponseToJSON(
  tokenGetListResponse: TokenGetListResponse,
): string {
  return JSON.stringify(
    TokenGetListResponse$outboundSchema.parse(tokenGetListResponse),
  );
}

export function tokenGetListResponseFromJSON(
  jsonString: string,
): SafeParseResult<TokenGetListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenGetListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenGetListResponse' from JSON`,
  );
}
