/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type VciMetadataRequest = {
  /**
   * The flag indicating whether the metadata is written in the pretty
   *
   * @remarks
   * format or not.
   */
  pretty: boolean;
};

/** @internal */
export type VciMetadataRequest$Outbound = {
  pretty: boolean;
};

/** @internal */
export const VciMetadataRequest$outboundSchema: z.ZodType<
  VciMetadataRequest$Outbound,
  z.ZodTypeDef,
  VciMetadataRequest
> = z.object({
  pretty: z.boolean(),
});

export function vciMetadataRequestToJSON(
  vciMetadataRequest: VciMetadataRequest,
): string {
  return JSON.stringify(
    VciMetadataRequest$outboundSchema.parse(vciMetadataRequest),
  );
}
