/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CredentialOfferInfo,
  CredentialOfferInfo$inboundSchema,
} from "./credentialofferinfo.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The result of the `/vci/offer/info` API call.
 */
export const VciOfferInfoResponseAction = {
  Ok: "OK",
  Forbidden: "FORBIDDEN",
  NotFound: "NOT_FOUND",
  CallerError: "CALLER_ERROR",
  AuthleteError: "AUTHLETE_ERROR",
} as const;
/**
 * The result of the `/vci/offer/info` API call.
 */
export type VciOfferInfoResponseAction = ClosedEnum<
  typeof VciOfferInfoResponseAction
>;

export type VciOfferInfoResponse = {
  /**
   * The code which represents the result of the API call.
   */
  resultCode?: string | undefined;
  /**
   * A short message which explains the result of the API call.
   */
  resultMessage?: string | undefined;
  /**
   * The result of the `/vci/offer/info` API call.
   */
  action?: VciOfferInfoResponseAction | undefined;
  info?: CredentialOfferInfo | undefined;
};

/** @internal */
export const VciOfferInfoResponseAction$inboundSchema: z.ZodNativeEnum<
  typeof VciOfferInfoResponseAction
> = z.nativeEnum(VciOfferInfoResponseAction);

/** @internal */
export const VciOfferInfoResponse$inboundSchema: z.ZodType<
  VciOfferInfoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultCode: z.string().optional(),
  resultMessage: z.string().optional(),
  action: VciOfferInfoResponseAction$inboundSchema.optional(),
  info: CredentialOfferInfo$inboundSchema.optional(),
});

export function vciOfferInfoResponseFromJSON(
  jsonString: string,
): SafeParseResult<VciOfferInfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VciOfferInfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VciOfferInfoResponse' from JSON`,
  );
}
