/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CredentialIssuanceOrder,
  CredentialIssuanceOrder$Outbound,
  CredentialIssuanceOrder$outboundSchema,
} from "./credentialissuanceorder.js";

export type VciSingleIssueRequest = {
  /**
   * The access token that came along with the credential request.
   */
  accessToken?: string | undefined;
  order?: CredentialIssuanceOrder | undefined;
};

/** @internal */
export type VciSingleIssueRequest$Outbound = {
  accessToken?: string | undefined;
  order?: CredentialIssuanceOrder$Outbound | undefined;
};

/** @internal */
export const VciSingleIssueRequest$outboundSchema: z.ZodType<
  VciSingleIssueRequest$Outbound,
  z.ZodTypeDef,
  VciSingleIssueRequest
> = z.object({
  accessToken: z.string().optional(),
  order: CredentialIssuanceOrder$outboundSchema.optional(),
});

export function vciSingleIssueRequestToJSON(
  vciSingleIssueRequest: VciSingleIssueRequest,
): string {
  return JSON.stringify(
    VciSingleIssueRequest$outboundSchema.parse(vciSingleIssueRequest),
  );
}
