/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The verified claims validation schema set.
 *
 * @remarks
 */
export const VerifiedClaimsValidationSchema = {
  Standard: "standard",
  StandardPlusIdDocument: "standard+id_document",
} as const;
/**
 * The verified claims validation schema set.
 *
 * @remarks
 */
export type VerifiedClaimsValidationSchema = ClosedEnum<
  typeof VerifiedClaimsValidationSchema
>;

/** @internal */
export const VerifiedClaimsValidationSchema$inboundSchema: z.ZodNativeEnum<
  typeof VerifiedClaimsValidationSchema
> = z.nativeEnum(VerifiedClaimsValidationSchema);

/** @internal */
export const VerifiedClaimsValidationSchema$outboundSchema: z.ZodNativeEnum<
  typeof VerifiedClaimsValidationSchema
> = VerifiedClaimsValidationSchema$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VerifiedClaimsValidationSchema$ {
  /** @deprecated use `VerifiedClaimsValidationSchema$inboundSchema` instead. */
  export const inboundSchema = VerifiedClaimsValidationSchema$inboundSchema;
  /** @deprecated use `VerifiedClaimsValidationSchema$outboundSchema` instead. */
  export const outboundSchema = VerifiedClaimsValidationSchema$outboundSchema;
}
