/*
 * Main Authlete SDK export with serviceId constructor support
 * 
 * This file is NOT generated by Speakeasy, so it won't be overwritten.
 * It exports the enhanced Authlete class with serviceId support.
 */

// Re-export everything from the generated index, but override Authlete with our overlay
export * from "./index.js";

// Override: Export the overlay class (with serviceId support) instead of generated class
export { Authlete, type AuthleteOptions } from "./authlete-overlay.js";
